### ISSUE TITLE
校准出现问题

### ISSUE THREAD

**Issue by esdrtf** [CHNZYX/Auto_Simulated_Universe#10]
如下：
C:\Users\19492\DOWNLO~1\AUTO_S~3\AUTO_S~1>python align_angle.py
WARNING [2023-05-21 00:41:54,260] [utils.py:30] 等待游戏窗口

C:\Users\19492\DOWNLO~1\AUTO_S~3\AUTO_S~1>pause

人物有在动和转向，但是·很慢，最好显示的也是pause

**Comment by CHNZYX** [comment]
不确定问题原因，是否解决？若未解决请详细描述，也可以加群交流。

**Comment by esdrtf** [comment]
重新安装了一下然后设置又重新调了一下，现在是可以校准完成，但是之前都是转一个圈的，现在是转1个多接近2圈？然后进入模拟宇宙后地图识别的准确率很高，但是貌似没有按照target来走，我重新补充了地图画的更完整了也不行；没有QQ😭

**Comment by CHNZYX** [comment]
可以试试release版本，今天更新了校准代码，应该会精准很多。

**Comment by esdrtf** [comment]
辛苦大佬了！但是依然有问题，重新校准后尝试了三次，两次原地发呆，一次顶着墙一直走。我感觉可能是电脑的问题，换电脑前还是先手打吧，感谢大佬发电了！
