### ISSUE TITLE
仙舟的地图识别经常出问题&遗物选择建议

### ISSUE THREAD

**Issue by kotoricon** [CHNZYX/Auto_Simulated_Universe#104]
仙舟的地图识别经常出问题，尤其是那几个拐角和楼梯特别的多的就看脚本在反复退了进进了退半个小时都没进下一图
顺便既然目前不会自动进行祝福强化，那么像有些遗物比如像祝福强化费用减少30%的遗物应该是加入排除列表不选择的，完全没有任何意义

**Comment by yukiime** [comment]
你可以试着自己录下地图，看能不能解决地图识别的问题.

**Comment by jason21415** [comment]
地图识别最重要的就是解析度 渲染精度跟光照質量拉高一點看能不能解決
