### ISSUE TITLE
中途结算怎么避免？

### ISSUE THREAD

**Issue by coolxll** [CHNZYX/Auto_Simulated_Universe#108]
INFO [2023-07-10 21:22:22,176] [states.py:655] find: 1, debug: 0, show_map: 0
WARNING [2023-07-10 21:22:22,485] [utils.py:86] 等待游戏窗口
INFO [2023-07-10 21:22:23,486] [states.py:33] 当前版本：v4.97 stable
INFO [2023-07-10 21:22:23,487] [utils.py:26] 通知：初始计数：1  开始运行
INFO [2023-07-10 21:22:23,488] [states.py:62] 加载地图
INFO [2023-07-10 21:22:23,760] [states.py:68] 加载地图完成，共 53 张
INFO [2023-07-10 21:22:27,860] [utils.py:237] 匹配到图片 ./imgs/floor/ff5.jpg 相似度 0.996781 阈值 0.970000
INFO [2023-07-10 21:22:27,860] [utils.py:494] 当前层数：5
INFO [2023-07-10 21:22:31,414] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.990045 阈值 0.970000
INFO [2023-07-10 21:22:31,578] [utils.py:676] need_confirm 区域-战斗
INFO [2023-07-10 21:22:36,486] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.988429 阈值 0.970000
INFO [2023-07-10 21:22:36,539] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.988569 阈值 0.970000
INFO [2023-07-10 21:22:36,967] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.988139 阈值 0.970000
INFO [2023-07-10 21:22:36,975] [states.py:222] 识别到传送点
INFO [2023-07-10 21:22:38,217] [states.py:234] 地图-1已完成,相似度-1,进入6层
INFO [2023-07-10 21:22:38,684] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:22:39,261] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:22:42,516] [states.py:292] 地图编号：30797  相似度：0.5802139037433155
INFO [2023-07-10 21:22:42,749] [states.py:322] target {((164.71428571428572, 40.357142857142854), 3), ((138.12820512820514, 38.61538461538461), 1), ((46.5, 17.875), 1), ((95.3913043478261, 36.95652173913044), 1), ((57.57142857142857, 38.857142857142854), 0)}
INFO [2023-07-10 21:22:45,547] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.987479 阈值 0.940000
INFO [2023-07-10 21:22:45,655] [utils.py:890] 进入新地图或者进入战斗 12.13530489934225
INFO [2023-07-10 21:22:47,273] [utils.py:948] removed:((46.5, 17.875), 1)
INFO [2023-07-10 21:22:47,342] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:22:47,932] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:22:48,531] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:22:49,517] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:22:50,111] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:23:26,018] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.970777 阈值 0.970000
INFO [2023-07-10 21:23:28,632] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991270 阈值 0.970000
INFO [2023-07-10 21:23:29,070] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991655 阈值 0.970000
INFO [2023-07-10 21:23:29,746] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:23:30,303] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.979913 阈值 0.955000
INFO [2023-07-10 21:23:31,249] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.981199 阈值 0.970000
INFO [2023-07-10 21:23:32,210] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.981629 阈值 0.970000
INFO [2023-07-10 21:23:33,169] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.981692 阈值 0.970000
INFO [2023-07-10 21:23:33,199] [utils.py:237] 匹配到图片 ./imgs/arrow.jpg 相似度 0.998672 阈值 0.970000
INFO [2023-07-10 21:23:34,059] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.981779 阈值 0.970000
INFO [2023-07-10 21:23:34,151] [utils.py:237] 匹配到图片 ./imgs/star.jpg 相似度 0.990913 阈值 0.965000
INFO [2023-07-10 21:23:49,512] [utils.py:890] 进入新地图或者进入战斗 43.5158896618376
INFO [2023-07-10 21:24:02,245] [utils.py:890] 进入新地图或者进入战斗 59.769113585325236
INFO [2023-07-10 21:24:15,697] [utils.py:890] 进入新地图或者进入战斗 59.769113585325236
INFO [2023-07-10 21:24:29,869] [utils.py:890] 进入新地图或者进入战斗 58.17145663765812
INFO [2023-07-10 21:24:34,062] [utils.py:26] 通知：地图30797，当前层数:6  暂离
ERROR [2023-07-10 21:24:34,064] [states.py:362] 地图30797未发现目标,相似度0.5802139037433155，尝试暂离
INFO [2023-07-10 21:24:34,558] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:35,127] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:35,689] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:36,651] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:37,219] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:37,801] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:38,793] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.989937 阈值 0.970000
INFO [2023-07-10 21:24:39,235] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.993061 阈值 0.970000
INFO [2023-07-10 21:24:39,929] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:40,476] [utils.py:237] 匹配到图片 ./imgs/init.jpg 相似度 0.976900 阈值 0.955000
INFO [2023-07-10 21:24:41,360] [utils.py:237] 匹配到图片 ./imgs/init.jpg 相似度 0.995418 阈值 0.970000
INFO [2023-07-10 21:24:42,228] [utils.py:237] 匹配到图片 ./imgs/init.jpg 相似度 0.995325 阈值 0.970000
INFO [2023-07-10 21:24:43,127] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:43,708] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:44,290] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:45,254] [utils.py:237] 匹配到图片 ./imgs/init.jpg 相似度 0.995070 阈值 0.970000
INFO [2023-07-10 21:24:46,130] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:24:46,689] [utils.py:237] 匹配到图片 ./imgs/begin.jpg 相似度 0.996354 阈值 0.955000
INFO [2023-07-10 21:24:46,690] [utils.py:237] 匹配到图片 ./imgs/conti.jpg 相似度 0.999057 阈值 0.955000
INFO [2023-07-10 21:24:56,143] [utils.py:237] 匹配到图片 ./imgs/floor/ff6.jpg 相似度 0.996559 阈值 0.955000
INFO [2023-07-10 21:24:56,143] [utils.py:494] 当前层数：6
INFO [2023-07-10 21:25:00,679] [states.py:292] 地图编号：30797  相似度：0.536986301369863
INFO [2023-07-10 21:25:00,909] [states.py:322] target {((164.71428571428572, 40.357142857142854), 3), ((138.12820512820514, 38.61538461538461), 1), ((46.5, 17.875), 1), ((95.3913043478261, 36.95652173913044), 1), ((57.57142857142857, 38.857142857142854), 0)}
INFO [2023-07-10 21:25:04,210] [utils.py:890] 进入新地图或者进入战斗 9.540210951546092
INFO [2023-07-10 21:25:05,821] [utils.py:948] removed:((46.5, 17.875), 1)
INFO [2023-07-10 21:25:09,085] [utils.py:876] removed:((57.57142857142857, 38.857142857142854), 0)
INFO [2023-07-10 21:25:11,966] [utils.py:890] 进入新地图或者进入战斗 6.684066769731636
INFO [2023-07-10 21:25:13,570] [utils.py:948] removed:((95.3913043478261, 36.95652173913044), 1)
INFO [2023-07-10 21:25:13,661] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:25:14,236] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:25:14,821] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:25:15,809] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:25:16,379] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:25:41,581] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.971137 阈值 0.970000
INFO [2023-07-10 21:25:50,244] [utils.py:890] 进入新地图或者进入战斗 9.818102402182936
INFO [2023-07-10 21:25:55,456] [utils.py:948] removed:((138.12820512820514, 38.61538461538461), 1)
INFO [2023-07-10 21:25:59,044] [utils.py:890] 进入新地图或者进入战斗 6.181357753234273
INFO [2023-07-10 21:26:47,654] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.974982 阈值 0.970000
INFO [2023-07-10 21:26:50,960] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.978306 阈值 0.970000
INFO [2023-07-10 21:26:54,305] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991343 阈值 0.970000
INFO [2023-07-10 21:26:54,733] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991228 阈值 0.970000
INFO [2023-07-10 21:26:54,742] [states.py:222] 识别到传送点
INFO [2023-07-10 21:26:55,988] [states.py:234] 地图30797已完成,相似度0.536986301369863,进入7层
INFO [2023-07-10 21:26:58,826] [utils.py:237] 匹配到图片 ./imgs/z.jpg 相似度 0.995647 阈值 0.970000
INFO [2023-07-10 21:27:00,929] [utils.py:237] 匹配到图片 ./imgs/z.jpg 相似度 0.995647 阈值 0.970000
INFO [2023-07-10 21:27:01,941] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:27:02,518] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:27:03,096] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:27:04,057] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:27:04,636] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:27:05,215] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:27:48,867] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.975689 阈值 0.970000
INFO [2023-07-10 21:27:57,355] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992587 阈值 0.970000
INFO [2023-07-10 21:27:57,464] [utils.py:676] need_confirm 区域-精英
INFO [2023-07-10 21:27:57,899] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991448 阈值 0.970000
INFO [2023-07-10 21:27:57,946] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991449 阈值 0.970000
INFO [2023-07-10 21:27:58,378] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991470 阈值 0.970000
INFO [2023-07-10 21:27:58,383] [states.py:222] 识别到传送点
INFO [2023-07-10 21:27:59,631] [states.py:234] 地图-1已完成,相似度-1,进入8层
INFO [2023-07-10 21:28:02,450] [utils.py:237] 匹配到图片 ./imgs/z.jpg 相似度 0.971265 阈值 0.970000
INFO [2023-07-10 21:28:04,552] [utils.py:237] 匹配到图片 ./imgs/z.jpg 相似度 0.971265 阈值 0.970000
INFO [2023-07-10 21:28:05,557] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:28:06,128] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:28:06,699] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:28:07,684] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:28:08,262] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:28:08,834] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:31:26,862] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.970205 阈值 0.970000
INFO [2023-07-10 21:31:31,055] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:31:31,605] [utils.py:237] 匹配到图片 ./imgs/strange.jpg 相似度 0.968064 阈值 0.955000
INFO [2023-07-10 21:31:43,882] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992650 阈值 0.970000
INFO [2023-07-10 21:31:43,990] [utils.py:676] need_confirm 区域-休整
INFO [2023-07-10 21:31:44,429] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991691 阈值 0.970000
INFO [2023-07-10 21:31:44,473] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991688 阈值 0.970000
INFO [2023-07-10 21:31:44,907] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991695 阈值 0.970000
INFO [2023-07-10 21:31:44,913] [states.py:222] 识别到传送点
INFO [2023-07-10 21:31:46,162] [states.py:234] 地图-1已完成,相似度-1,进入9层
INFO [2023-07-10 21:31:46,611] [utils.py:237] 匹配到图片 ./imgs/yes.jpg 相似度 0.998942 阈值 0.970000
INFO [2023-07-10 21:31:47,478] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:31:48,497] [utils.py:551] 黑塔相似度0.9597886800765991，位置87,165
INFO [2023-07-10 21:31:50,189] [utils.py:551] 黑塔相似度0.8829176425933838，位置91,161
INFO [2023-07-10 21:32:06,894] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.990825 阈值 0.970000
INFO [2023-07-10 21:32:43,564] [utils.py:26] 通知：地图-1，当前层数:9  暂离
ERROR [2023-07-10 21:32:43,565] [states.py:362] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-07-10 21:32:44,036] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:44,603] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:45,175] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:46,135] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:46,703] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:47,275] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:48,217] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.988763 阈值 0.970000
INFO [2023-07-10 21:32:48,652] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992846 阈值 0.970000
INFO [2023-07-10 21:32:49,321] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:49,866] [utils.py:237] 匹配到图片 ./imgs/init.jpg 相似度 0.995765 阈值 0.955000
INFO [2023-07-10 21:32:50,730] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:32:51,269] [utils.py:237] 匹配到图片 ./imgs/begin.jpg 相似度 0.996350 阈值 0.955000
INFO [2023-07-10 21:32:51,271] [utils.py:237] 匹配到图片 ./imgs/conti.jpg 相似度 0.999058 阈值 0.955000
INFO [2023-07-10 21:33:00,143] [utils.py:237] 匹配到图片 ./imgs/floor/ff9.jpg 相似度 0.996655 阈值 0.955000
INFO [2023-07-10 21:33:00,143] [utils.py:494] 当前层数：9
INFO [2023-07-10 21:33:02,452] [utils.py:551] 黑塔相似度0.9648089408874512，位置87,167
INFO [2023-07-10 21:33:04,329] [utils.py:551] 黑塔相似度0.8878691792488098，位置91,157
INFO [2023-07-10 21:33:05,932] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992552 阈值 0.970000
INFO [2023-07-10 21:33:05,980] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992672 阈值 0.970000
INFO [2023-07-10 21:33:06,034] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992484 阈值 0.970000
INFO [2023-07-10 21:33:06,097] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991499 阈值 0.970000
INFO [2023-07-10 21:33:06,156] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991489 阈值 0.970000
INFO [2023-07-10 21:33:06,217] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991474 阈值 0.970000
INFO [2023-07-10 21:33:06,282] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991327 阈值 0.970000
INFO [2023-07-10 21:33:06,342] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991324 阈值 0.970000
INFO [2023-07-10 21:33:06,400] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991367 阈值 0.970000
INFO [2023-07-10 21:33:06,460] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991379 阈值 0.970000
INFO [2023-07-10 21:33:06,510] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991461 阈值 0.970000
INFO [2023-07-10 21:33:06,567] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991452 阈值 0.970000
INFO [2023-07-10 21:33:06,627] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991490 阈值 0.970000
INFO [2023-07-10 21:33:06,682] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.983201 阈值 0.970000
INFO [2023-07-10 21:33:11,792] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.987786 阈值 0.970000
INFO [2023-07-10 21:33:11,900] [utils.py:676] need_confirm 黑塔
INFO [2023-07-10 21:33:12,339] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992079 阈值 0.970000
INFO [2023-07-10 21:33:12,387] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992078 阈值 0.970000
INFO [2023-07-10 21:33:12,818] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992078 阈值 0.970000
INFO [2023-07-10 21:33:13,521] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:33:14,071] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.981508 阈值 0.955000
INFO [2023-07-10 21:33:15,009] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.982632 阈值 0.970000
INFO [2023-07-10 21:33:15,953] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.983013 阈值 0.970000
INFO [2023-07-10 21:33:16,894] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.983123 阈值 0.970000
INFO [2023-07-10 21:33:16,926] [utils.py:237] 匹配到图片 ./imgs/arrow.jpg 相似度 0.998694 阈值 0.970000
INFO [2023-07-10 21:33:17,789] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.982881 阈值 0.970000
INFO [2023-07-10 21:33:17,880] [utils.py:237] 匹配到图片 ./imgs/star.jpg 相似度 0.990913 阈值 0.965000
INFO [2023-07-10 21:33:17,909] [utils.py:237] 匹配到图片 ./imgs/events/0.jpg 相似度 0.975680 阈值 0.965000
INFO [2023-07-10 21:33:20,655] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.978716 阈值 0.970000
INFO [2023-07-10 21:33:23,258] [utils.py:237] 匹配到图片 ./imgs/event.jpg 相似度 0.979802 阈值 0.970000
INFO [2023-07-10 21:33:26,356] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.992372 阈值 0.970000
INFO [2023-07-10 21:33:26,463] [utils.py:676] need_confirm 区域-事件
INFO [2023-07-10 21:33:26,897] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991072 阈值 0.970000
INFO [2023-07-10 21:33:26,949] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991068 阈值 0.970000
INFO [2023-07-10 21:33:27,393] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991062 阈值 0.970000
INFO [2023-07-10 21:33:27,399] [states.py:222] 识别到传送点
INFO [2023-07-10 21:33:28,643] [states.py:234] 地图-1已完成,相似度-1,进入10层
INFO [2023-07-10 21:33:29,109] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:33:29,691] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:33:30,684] [utils.py:540] 交互点相似度0.9415678381919861，位置89,66
INFO [2023-07-10 21:33:33,422] [utils.py:540] 交互点相似度0.8861917853355408，位置108,90
INFO [2023-07-10 21:34:25,540] [utils.py:26] 通知：地图-1，当前层数:10  暂离
ERROR [2023-07-10 21:34:25,541] [states.py:362] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-07-10 21:34:26,037] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:26,615] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:27,184] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:28,141] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:28,712] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:29,273] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:30,214] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991112 阈值 0.970000
INFO [2023-07-10 21:34:30,655] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.993132 阈值 0.970000
INFO [2023-07-10 21:34:31,337] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:31,887] [utils.py:237] 匹配到图片 ./imgs/init.jpg 相似度 0.965724 阈值 0.955000
INFO [2023-07-10 21:34:32,761] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:34:33,313] [utils.py:237] 匹配到图片 ./imgs/begin.jpg 相似度 0.996353 阈值 0.955000
INFO [2023-07-10 21:34:33,314] [utils.py:237] 匹配到图片 ./imgs/conti.jpg 相似度 0.999058 阈值 0.955000
INFO [2023-07-10 21:34:42,763] [utils.py:237] 匹配到图片 ./imgs/floor/ff10.jpg 相似度 0.997068 阈值 0.955000
INFO [2023-07-10 21:34:42,764] [utils.py:494] 当前层数：10
INFO [2023-07-10 21:34:45,053] [utils.py:540] 交互点相似度0.9413871169090271，位置89,66
INFO [2023-07-10 21:34:48,168] [utils.py:540] 交互点相似度0.8840195536613464，位置112,95
INFO [2023-07-10 21:35:28,738] [utils.py:26] 通知：地图-1，当前层数:10  中途结算
ERROR [2023-07-10 21:35:29,141] [states.py:371] 地图-1未发现目标,相似度-1，尝试退出重进
INFO [2023-07-10 21:35:29,577] [utils.py:237] 匹配到图片 ./imgs/yes.jpg 相似度 0.998942 阈值 0.970000
INFO [2023-07-10 21:35:30,440] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:31,015] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:31,575] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:32,536] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:33,109] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:33,677] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:34,643] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:35,217] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:35,799] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:36,754] [utils.py:237] 匹配到图片 ./imgs/init.jpg 相似度 0.979811 阈值 0.970000
INFO [2023-07-10 21:35:37,630] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:38,175] [utils.py:237] 匹配到图片 ./imgs/begin.jpg 相似度 0.996345 阈值 0.955000
INFO [2023-07-10 21:35:39,442] [utils.py:237] 匹配到图片 ./imgs/start.jpg 相似度 0.984433 阈值 0.970000
INFO [2023-07-10 21:35:40,303] [utils.py:237] 匹配到图片 ./imgs/start.jpg 相似度 0.983231 阈值 0.970000
INFO [2023-07-10 21:35:41,149] [utils.py:237] 匹配到图片 ./imgs/yes.jpg 相似度 0.998942 阈值 0.970000
INFO [2023-07-10 21:35:42,019] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:42,576] [utils.py:237] 匹配到图片 ./imgs/fate.jpg 相似度 0.986943 阈值 0.955000
INFO [2023-07-10 21:35:43,460] [utils.py:237] 匹配到图片 ./imgs/fate_2.jpg 相似度 0.994492 阈值 0.970000
INFO [2023-07-10 21:35:44,310] [utils.py:237] 匹配到图片 ./imgs/fate_2.jpg 相似度 0.994260 阈值 0.970000
INFO [2023-07-10 21:35:45,186] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:45,762] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:46,334] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:47,307] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:47,862] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:48,435] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:49,411] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:35:49,970] [utils.py:237] 匹配到图片 ./imgs/fate_3.jpg 相似度 0.966661 阈值 0.955000
INFO [2023-07-10 21:35:51,487] [states.py:292] 地图编号：91571  相似度：0.7540983606557377
INFO [2023-07-10 21:35:51,659] [states.py:322] target {((72.77272727272727, 30.613636363636363), 1), ((90.06896551724138, 14.586206896551724), 3), ((48.75609756097561, 71.48780487804878), 1)}
INFO [2023-07-10 21:35:56,104] [utils.py:890] 进入新地图或者进入战斗 8.001821624847897
INFO [2023-07-10 21:35:57,708] [utils.py:948] removed:((48.75609756097561, 71.48780487804878), 1)
INFO [2023-07-10 21:36:00,775] [utils.py:890] 进入新地图或者进入战斗 29.315230647802927
INFO [2023-07-10 21:36:06,065] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:36:06,635] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:36:07,198] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:36:28,812] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.978663 阈值 0.970000
INFO [2023-07-10 21:36:31,885] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.979727 阈值 0.970000
INFO [2023-07-10 21:36:34,943] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.974777 阈值 0.970000
INFO [2023-07-10 21:36:38,000] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.973680 阈值 0.970000
INFO [2023-07-10 21:36:44,422] [utils.py:890] 进入新地图或者进入战斗 9.552297330879135
INFO [2023-07-10 21:36:49,634] [utils.py:948] removed:((72.77272727272727, 30.613636363636363), 1)
INFO [2023-07-10 21:36:49,703] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:37:10,894] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.970023 阈值 0.970000
INFO [2023-07-10 21:37:17,725] [utils.py:890] 进入新地图或者进入战斗 6.772417304585087
INFO [2023-07-10 21:37:21,196] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991266 阈值 0.970000
INFO [2023-07-10 21:37:21,205] [utils.py:924] removed:((90.06896551724138, 14.586206896551724), 3)
INFO [2023-07-10 21:37:21,254] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991258 阈值 0.970000
INFO [2023-07-10 21:37:21,695] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991215 阈值 0.970000
INFO [2023-07-10 21:37:21,701] [states.py:222] 识别到传送点
INFO [2023-07-10 21:37:22,948] [states.py:234] 地图91571已完成,相似度0.7540983606557377,进入2层
INFO [2023-07-10 21:37:26,480] [utils.py:237] 匹配到图片 ./imgs/z.jpg 相似度 0.983714 阈值 0.970000
INFO [2023-07-10 21:37:28,583] [utils.py:237] 匹配到图片 ./imgs/z.jpg 相似度 0.983714 阈值 0.970000
INFO [2023-07-10 21:37:29,594] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:37:30,169] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:37:30,751] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:37:31,734] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:37:32,302] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:37:32,863] [states.py:467] 匹配不到任何图标
INFO [2023-07-10 21:37:46,953] [utils.py:237] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.971880 阈值 0.970000
INFO [2023-07-10 21:37:54,049] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.974209 阈值 0.970000
INFO [2023-07-10 21:37:54,158] [utils.py:676] need_confirm 区域-战斗
INFO [2023-07-10 21:37:55,485] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991084 阈值 0.970000
INFO [2023-07-10 21:37:55,537] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991082 阈值 0.970000
INFO [2023-07-10 21:37:55,967] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.991136 阈值 0.970000
INFO [2023-07-10 21:37:55,974] [states.py:222] 识别到传送点
INFO [2023-07-10 21:37:57,210] [states.py:234] 地图-1已完成,相似度-1,进入3层

比如这里的log里第10层就中途结算了一次

**Comment by jason21415** [comment]
就我自己的經驗 拉高渲染精度+光照質量 他如果找的到圖就不會中途離開
我原本設定1920X1080 渲染精度1.4 其他設置全部最高 沒有發生過中途離開 60+場都沒事
改成設定1920X1080 渲染精度1.0 光照質量中 其他設置全部最低 就有低機會發生中途離開 10幾場就出現1次
