### ISSUE TITLE
It doesn't work 

### ISSUE THREAD

**Issue by ArthaVerx** [CHNZYX/Auto_Simulated_Universe#109]
C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1>python states.py --find=1
INFO [2023-07-15 01:45:05,148] [states.py:656] find: 1, debug: 0, show_map: 0
WARNING [2023-07-15 01:45:05,362] [utils.py:86] 等待游戏窗口
INFO [2023-07-15 01:45:06,363] [states.py:33] 当前版本：v4.97 stable
INFO [2023-07-15 01:45:06,363] [utils.py:26] 通知：初始计数：0  开始运行
INFO [2023-07-15 01:45:06,364] [states.py:62] 加载地图
INFO [2023-07-15 01:45:06,567] [states.py:68] 加载地图完成，共 53 张
INFO [2023-07-15 01:45:06,684] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.994952 阈值 0.970000
INFO [2023-07-15 01:45:07,109] [utils.py:237] 匹配到图片 ./imgs/f.jpg 相似度 0.994951 阈值 0.970000
INFO [2023-07-15 01:45:07,769] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:08,318] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:08,869] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:09,847] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:10,393] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:10,943] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:11,913] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:12,468] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:13,019] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:13,977] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:14,523] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:15,074] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:16,027] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:16,580] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:17,135] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:18,117] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:18,651] [utils.py:237] 匹配到图片 ./imgs/start.jpg 相似度 0.962171 阈值 0.955000
INFO [2023-07-15 01:45:19,489] [utils.py:237] 匹配到图片 ./imgs/yes.jpg 相似度 0.978744 阈值 0.970000
INFO [2023-07-15 01:45:20,341] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:20,894] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:21,447] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:22,416] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:22,968] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:23,521] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:24,472] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:25,007] [utils.py:237] 匹配到图片 ./imgs/fate_2.jpg 相似度 0.984531 阈值 0.955000
INFO [2023-07-15 01:45:25,861] [utils.py:237] 匹配到图片 ./imgs/fate_2.jpg 相似度 0.984184 阈值 0.970000
INFO [2023-07-15 01:45:26,719] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:27,273] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:27,819] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:28,846] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:29,398] [states.py:467] 匹配不到任何图标
INFO [2023-07-15 01:45:37,924] [states.py:292] 地图编号：30797  相似度：0.38095238095238093
地图文件： imgs/maps/30797/map_4079_4073_.jpg
INFO [2023-07-15 01:45:38,086] [states.py:322] target {((164.71428571428572, 40.357142857142854), 3), ((138.12820512820514, 38.61538461538461), 1), ((46.5, 17.875), 1), ((95.3913043478261, 36.95652173913044), 1), ((57.57142857142857, 38.857142857142854), 0)}
Traceback (most recent call last):
  File "C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1\states.py", line 659, in main
    su.start()
  File "C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1\states.py", line 648, in start
    self.route()
  File "C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1\states.py", line 118, in route
    res = self.normal()
          ^^^^^^^^^^^^^
  File "C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1\states.py", line 386, in normal
    self.get_direc()
  File "C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1\utils\utils.py", line 734, in get_direc
    self.get_loc(bw_map, 40 - self.find * 15)
  File "C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1\utils\utils.py", line 1010, in get_loc
    tbw = cv.resize(bw_map, (176 + tt * 2, 176 + tt * 2))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

INFO [2023-07-15 01:45:38,323] [states.py:590] 尝试停止运行

C:\Users\Artha\Desktop\AUTO_S~1\AUTO_S~1>pause
Press any key to continue . . .

It only shows this in log
It didnt click the world, didnt choose the character even thou i've done the 'info' edit. didn't choose the blessing. All it does was just pressing continue and checking the map route after spawning inside the simulated universe world. it didnt move.
Can anyone help me?

**Comment by ArthaVerx** [comment]
1 3 5 7
0.32786885245901637
3
巡猎

0
0
0
0

Here are my 'info'

**Comment by gitzwz** [comment]
Have not tried myself, but I guess you may have the wrong 5th line of your info. Here is the content of info_example.txt.

9 3 5 1
0.7092198581560284
2
巡猎
422caa5684f4cf3afcd1da0f5840e9461e74c03f

**Comment by ArthaVerx** [comment]
i already fixed it, after i changed my monitor resolution to 1366 x 768 it worked
