### ISSUE TITLE
'均晶转变','零维强化' 更换位置

### ISSUE THREAD

**Issue by Jacheers** [CHNZYX/Auto_Simulated_Universe#110]
切换ocr.py里105行 '零维强化'，'均晶转变'的位置，**充能**打的更快一点。

还有echo文件夹里面，什么火堆外的夜。请提供一个选项禁用优先祝福，因为有时候这些没什么用。

**Comment by aoounn** [comment]
这个挺重要的，或者有可以修改自定义的

**Comment by ayssia** [comment]
这个我是通过把`imgs\bless\0\echo1.jpg`和`imgs\bless\0\echo2.jpg`文件名对调解决了。
