### ISSUE TITLE
有概率朝着地板旋转普攻导致识别不到下一层入口

### ISSUE THREAD

**Issue by UMP45-Team404** [CHNZYX/Auto_Simulated_Universe#111]
1号位为艾丝妲，开怪时经常整个画面朝着地板转一圈同时普攻。大部分情况下打完怪后能马上找到下一层入口，但有概率直接开始 朝地板转圈→普攻→水平转圈找入口（但此时主视角是对着地板的）→直走（此时视角回正，但不识别入口）循环，多次循环后暂离再入重复循环。

**Comment by UMP45-Team404** [comment]
运行环境补充：游戏设置同README最低设置，渲染精度1.0和1.2均有此问题。python版和gui版也有此问题。游戏和gui运行在虚拟机中，点击运行后使用键盘热键将鼠标从虚拟机释放控制。

**Comment by freefrank** [comment]
> 运行环境补充：游戏设置同README最低设置，渲染精度1.0和1.2均有此问题。python版和gui版也有此问题。游戏和gui运行在虚拟机中，点击运行后使用键盘热键将鼠标从虚拟机释放控制。

请问怎么让游戏跑在虚拟机中？用vmware还是hyperv? 在vmware里游戏提示不能用虚拟机环境运行。

**Comment by UMP45-Team404** [comment]
> > 运行环境补充：游戏设置同README最低设置，渲染精度1.0和1.2均有此问题。python版和gui版也有此问题。游戏和gui运行在虚拟机中，点击运行后使用键盘热键将鼠标从虚拟机释放控制。
> 
> 请问怎么让游戏跑在虚拟机中？用vmware还是hyperv? 在vmware里游戏提示不能用虚拟机环境运行。

vmware使用去模拟化的系统镜像就可以了
