### ISSUE TITLE
世界七新的仙舟区域地图支持不佳

### ISSUE THREAD

**Issue by yutouyes** [CHNZYX/Auto_Simulated_Universe#112]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/17039457/54f66c84-e074-4130-937d-248a71ac79ce)
比如这处场景，无法自动点击与寻路

**Comment by yutouyes** [comment]
可能和事件左边的<!>有关，如果是其他地图的气泡图标就可以正常识别，比如这个
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/17039457/f3326fbe-2bb4-484c-8d37-72fc6694c0bf)

**Comment by yutouyes** [comment]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/17039457/b1f3848b-b95b-434b-8a8c-a0a54f19ef21)
这个也无法寻路

**Comment by Klamist** [comment]
居然有两种F交互图标吗……
