### ISSUE TITLE
No module named 'win32gui' 无法解决

### ISSUE THREAD

**Issue by dianayyds** [CHNZYX/Auto_Simulated_Universe#115]
states.py中  No module named 'win32gui' 和No module named 'win32api' 参照网上的方法都无法解决

**Comment by lingkai5wu** [comment]
给开发者的可能的解决方法：
方法1：https://cloud.tencent.com/developer/article/1730385
方法2也是本人在用的，不需要修改库文件：
1. import pywintypes
2. 随便打印一下pywintypes，防止IDE警告

**Comment by dianayyds** [comment]
啥叫打印一下pywintypes，直接import这个包会出现Unused import statement 'import pywintypes' ，也pip不下来

**Comment by lingkai5wu** [comment]
参照我一个项目中的这部分：https://github.com/lingkai5wu/AutoMuteBG/blob/master/main.py
