### ISSUE TITLE
计数统计能换成或者添加 统计杀死精英怪吗？

### ISSUE THREAD

**Issue by zzb-yy** [CHNZYX/Auto_Simulated_Universe#116]
杀一次精英怪计一次，现在按轮次我不清楚啥时候满100只，因为有可能是中途GG下车的。不知道好不好实现？

**Comment by Eric-Joker** [comment]
第一只精英怪一倍掉落
第二只两倍
boss三倍
每周只会掉240单位的掉落
希望把计数改成记这个（
