### ISSUE TITLE
4.9.7stable打怪时会匹配不到图标卡住

### ISSUE THREAD

**Issue by akariiowo** [CHNZYX/Auto_Simulated_Universe#117]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/135534698/e7aa9ca0-28e5-4bea-b195-a32f3c1ba537)
画面配置已经调到最高，分辨率1920*1080全屏，每次进入战斗后就会卡住，显示匹配不到图标，打的是第三宇宙和第四宇宙，都会有这个问题
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/135534698/1928be8a-d55b-4784-9b33-48b4cc0762a1)

**Comment by akariiowo** [comment]
![6812T_G{V2F5VA6JLI9R7MV](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/135534698/6926a37b-d8b2-41b8-b817-c2047f18ed6b)
![d0e201e3400766274247483609f27b7e](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/135534698/392853a2-7136-4eee-a2d0-84def022cba4)
电脑和平板对比了下画面，好像电脑端的人物黑了一点，但是画质都是选的非常高，不太明白是怎么回事

**Comment by akariiowo** [comment]
更新到5.08不会有问题了，不过想问一下下载地图为什么总下载失败

**Comment by jason21415** [comment]
> 更新到5.08不會有問題了，不過想問一下下載地圖為什麼總下載失敗

可能跟你的網路有問題
