### ISSUE TITLE
游戏更新后就报这个错，更新到5.08版本后还是相同的报错

### ISSUE THREAD

**Issue by Ikeltis** [CHNZYX/Auto_Simulated_Universe#120]
C:\PROGRA~4\AUTO_S~1.08>python states.py --find=1
INFO [2023-07-25 22:07:20,511] [states.py:669] find: 1, debug: 0, show_map: 0
WARNING [2023-07-25 22:07:20,875] [utils.py:86] 等待游戏窗口
INFO [2023-07-25 22:07:21,877] [states.py:33] 当前版本：v5.08
INFO [2023-07-25 22:07:21,878] [utils.py:26] 通知：初始计数：0  开始运行
INFO [2023-07-25 22:07:21,879] [states.py:63] 加载地图
INFO [2023-07-25 22:07:22,227] [states.py:69] 加载地图完成，共 63 张
Traceback (most recent call last):
  File "C:\PROGRA~4\AUTO_S~1.08\states.py", line 672, in main
    su.start()
  File "C:\PROGRA~4\AUTO_S~1.08\states.py", line 661, in start
    self.route()
  File "C:\PROGRA~4\AUTO_S~1.08\states.py", line 118, in route
    self.get_screen() #0.9734,0.3009   0.3750,0.9398   0.1562,0.2250
    ^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~4\AUTO_S~1.08\utils\utils.py", line 347, in get_screen
    screen_raw = pyautogui.screenshot(region=[self.x0,self.y0,self.xx,self.yy])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: couldNotImportPyScreeze() got an unexpected keyword argument 'region'
INFO [2023-07-25 22:07:22,340] [states.py:603] 尝试停止运行

**Comment by omg-xtao** [comment]
未安装完整依赖
