### ISSUE TITLE
当前版本优先选择事件层

### ISSUE THREAD

**Issue by Abbott-Z** [CHNZYX/Auto_Simulated_Universe#121]
当前版本（Auto_Simulated_Universe_v5.08  2023.07.24）在同时有事件层传送门和战斗层传送门时会优先选择进入事件层，容易导致高难度下祝福不够翻车，希望能支持优先选择进入战斗层。

**Comment by bin1129** [comment]
事件层和战斗层位置感觉是随机的，脚本只是选了一个没去判断而已，以前也这样，容易翻车是因为最高难度敌人强度加强不少。我是通过控制事件选项曲线救国的，事件选项默认选最下边那个，但有办法控制，把事件选项截图重命名成数字编号放在imgs/events文件夹里，事件就会优先按截图选项选择了，我昨天手动打了好几把特意全选事件层，把我觉得有利的选项都截图放好了，昨晚挂机世界6难度4用欢愉克罗艾景打了4个小时10把都没翻车

**Comment by jason21415** [comment]
> 當前版本（Auto_Simulated_Universe_v5.08 2023.07.24）在同時有事件層傳送門和戰鬥層傳送門時會優先選擇進入事件層，容易導致高難度下祝福不夠翻車，希望能支持優先選擇進入戰鬥層。

會翻車就打前一個難度的關卡 獎勵沒差很多 穩定性比較重要
