### ISSUE TITLE
Any Develop instructions?有開發指引嗎

### ISSUE THREAD

**Issue by bookbug666** [CHNZYX/Auto_Simulated_Universe#122]
有wiki或是任何開發指引嗎？我完全沒有看到如
- 截圖應該有什麼指定大小、保留多少邊緣
- 如何調整祝福優先度
- 如何讓ASU更傾向於戰鬥而非事件
- 修改應使用哪一個branch

另外看了原碼
- 是否有最終戰強化的選項（有看到mask檔案
小問題如
- 海外是否有Discord群組能參與討論，不方便用QQ

以及問問題是在issue還是discussion那邊？（雖然我還有不少問題但我儘量一個issue問一個主要問題）

**Comment by CHNZYX** [comment]
项目基本只有我一人维护，没有开发指引。祝福优先级在ocr.py里。没有倾向事件或战斗的功能实现。修改可以直接pull request到主分支。没有最终强化祝福的功能。有telegram群，(https://t.me/+rVBc3yeywp9iZDA1)
