### ISSUE TITLE
詢問手動修改匹配其他語言的方法?

### ISSUE THREAD

**Issue by jason21415** [CHNZYX/Auto_Simulated_Universe#127]
如果我想在簡體中文區以外的版本(繁體中文/英文)使用
是不是只要更改 \imgs 資料夾中包含文字的圖片 重新截圖任何包含文字圖片(繁體中文/英文)並以同樣檔名覆蓋即可?

\imgs\bless 命途迴響
\imgs\events 事件
\imgs\echos 祝福

檔名0.JPG 1.JPG 2.JPG 3.JPG 4.JPG
檔名&副檔名有要求嗎?

**Comment by CHNZYX** [comment]
当前没有多语言支持，修改图片没有用
