### ISSUE TITLE
当前版本的暂离方式不好

### ISSUE THREAD

**Issue by ayssia** [CHNZYX/Auto_Simulated_Universe#130]
低几率情况下，从5层点击传送门进入6层后，log里并未记录已经进入6层，也就是程序认为当前仍在5层，这会导致程序无法推图。

以上情况本身并不严重，只要程序暂离模拟宇宙并再次进入即可，但当前版本尝试暂离并非离开模拟宇宙再进，而是在设置里选择脱离卡死，这无法改变“程序认为当前仍在5层”这一点，从而无法恢复正常运行。

**Comment by ayssia** [comment]
多挂了几次之后发现，程序在连续三次脱离卡死失败之后还是会退出重进的，但是感觉还不如直接退出重进来得快一点。

**Comment by CHNZYX** [comment]
下次更新会修复
