### ISSUE TITLE
关于GUI界面操作更改imgs文件夹图片无法正常生效的问题

### ISSUE THREAD

**Issue by Baisbt** [CHNZYX/Auto_Simulated_Universe#133]
我尝试修改一下虚无命途构造回响三个事件的选择优先级，仿照着imgs/bless先前就有的存护和巡猎命途做了一个虚无命途的文件夹
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/86550278/dea898d0-0f0e-4aa9-9f1e-1e1a69d44b47)
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/86550278/ac0f853a-fd90-4216-b16a-4bc1b47f5287)

然而在实际选择过程中，脚本反而会优先选择这俩个祝福之外的第三个祝福。
请问有什么解决办法嘛，还是说脚本其实无法识别这种修改的方式

**Comment by CHNZYX** [comment]
此方法已弃用，要做到想要的效果只能改代码
