### ISSUE TITLE
运行34次以后不会停止自动化

### ISSUE THREAD

**Issue by moesnow** [CHNZYX/Auto_Simulated_Universe#134]
https://github.com/CHNZYX/Auto_Simulated_Universe/blob/18bd25a0373eb26395b263c3e12b43b3232c7ef0/states.py#L97-L99

https://github.com/CHNZYX/Auto_Simulated_Universe/blob/18bd25a0373eb26395b263c3e12b43b3232c7ef0/states.py#L144-L148

[Auto_Simulated_Universe/states.py](https://github.com/CHNZYX/Auto_Simulated_Universe/blob/18bd25a0373eb26395b263c3e12b43b3232c7ef0/states.py#L144-L148) 147行应该改成`self._stop=1`吧

**Comment by JunNanLYS** [comment]
从0开始计数，每完成1次加1

**Comment by moesnow** [comment]
> 从0开始计数，每完成1次加1

确实是这样，但是和标题有什么关系，只要 `self._stop=0` while循环永远不会停止

**Comment by JunNanLYS** [comment]
`self._stop=1`会改变原来的意思，或许添加别的判断条件会更好？比如添加个`self._is_end=True`这样就能知道已经运行34次了，退出程序前再设置回False就行

**Comment by moesnow** [comment]
> `self._stop=1`会改变原来的意思，或许添加别的判断条件会更好？比如添加个`self._is_end=True`这样就能知道已经运行34次了，退出程序前再设置回False就行

```python
 def end_of_uni(self): 
     self.update_count(0) 
     if notif("已完成",f"计数:{self.count}",cnt=str(self.count)) >= 34 and self.debug != 2: 
         self._stop=0 
     self.floor = 0 
```
“原来的意思”是指什么，这一行“判断运行次数大于等于34且非调试模式”的目的难道不是为了停止运行吗？还是说要在配置文件中增加一个选项，判断是否要自动停止？感觉很难会有0收益还要挂机刷的需求吧。
