### ISSUE TITLE
It doesn't do immersions reward and doesn't choose the team

### ISSUE THREAD

**Issue by ArthaVerx** [CHNZYX/Auto_Simulated_Universe#137]
It completely ignore the immersions reward and just go straight to the next floor. Also when choosing a team, it doesn't do anything, just skip right through it

**Comment by Eric-Joker** [comment]
If a default team exists it will not select it. Immersion rewards require the corresponding switch to be turned on

**Comment by ArthaVerx** [comment]
what do you mean by "corresponding switch?" I already have it turned on in the gui. but it doesn't work.
i don't understand python, especially chinese. i've looked around at the code but didn't find anything about immersion

**Comment by ArthaVerx** [comment]
> If a default team exists it will not select it. Immersion rewards require the corresponding switch to be turned on

could you tell me how to turn on the immersion reward?

**Comment by Eric-Joker** [comment]
> > If a default team exists it will not select it. Immersion rewards require the corresponding switch to be turned on
> 
> could you tell me how to turn on the immersion reward?

I'm using the source code, but it should be the same as the release version
There's a switch at the bottom of the home page when you open the gui, that's the switch for the immersion bonus
I can't take a screenshot right now without my computer, I'll take one when I get home.

**Comment by Eric-Joker** [comment]
![4647985b2d4a1d9fe5a058919c45a75](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/60310368/51b1a506-7ac1-4ec5-9372-bff7585055d7)

**Comment by ArthaVerx** [comment]
like i said, I've turned it on. but it doesnt do anything

**Comment by Eric-Joker** [comment]
> like i said, I've turned it on. but it doesnt do anything

hmmm, that's probably because of the game's graphics settings, take a screenshot?

**Comment by ArthaVerx** [comment]
> > like i said, I've turned it on. but it doesnt do anything
> 
> hmmm, that's probably because of the game's graphics settings, take a screenshot?

![Screenshot 2023-08-24 220003](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/104915027/dd286731-553a-45ba-b5a2-f9fd20de9023)

**Comment by Eric-Joker** [comment]
it looks like everything is set up fine, except that it doesn't use Chinese.

**Comment by ArthaVerx** [comment]
Because im talking to you in english. So i had to changed it for better
understanding. Its still not working even if i changed it to chinese

**Comment by Eric-Joker** [comment]
Well, I don't know why then.
