### ISSUE TITLE
[Feat]: 有考虑添加安卓模拟器的支持吗？

### ISSUE THREAD

**Issue by Xuan0cheng** [CHNZYX/Auto_Simulated_Universe#140]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

RT，本地远程桌面使用起来不太方便，或许可以考虑通过adb支持安卓模拟器？

**Comment by Eric-Joker** [comment]
模拟器太卡了，隔壁有个项目原本也有模拟器支持，后来给删了。
