### ISSUE TITLE
[Bug]: 没有正确识别奇物优先级

### ISSUE THREAD

**Issue by bin1129** [CHNZYX/Auto_Simulated_Universe#142]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.20

### 重现步骤

作者，我看出新版本你想把全部优先级都能写在配置文件了，目前范例配置文件中，读取顺序是奇物、祝福，后来你还把事件优先级也在代码里加上了，但目前范例还没更新。
从ocr.py那里读取配置文件的代码self.blesses[i-2]中是i-2能看出你在配置文件中读取顺序是想把事件放在奇物后面，但我在配置文件的奇物后面加入事件以后，ocr.py那里的代码会使奇物优先级被事件优先级顶替掉，使得奇物优先级失效，目前我改成这样就正确了，可以参考下
for i,j in enumerate(config):
                if i==0:
                    self.strange = config[j]
                else:
                    self.blesses[i-2] = config[j]

### 期望的结果是什么？

正确读取配置文件奇物优先级

### 实际的结果是什么？

错误地把奇物优先级读取成事件优先级

**Comment by CHNZYX** [comment]
已修复

**Comment by bin1129** [comment]
> 已修复

作者你没懂我意思啊，我打了个log给你看
INFO [2023-08-14 22:04:33,483] [ocr.py:142] prior|['丰饶火漆', '购买1个星祝福', '跳上右边的砖块', '丢下雕像', '和序列扑 满玩', '信仰星神', '克里珀的恩赐', '哈克的藏品', '动作片', '感恩克里珀星神']|['火堆外的夜', '景星助狩月', '诸行无常', ' 诸法无我', '延彼遐龄', '施诸愿印', '回归不等式', '一法界心', '天人不动众', '厌离邪秽苦', '宝光烛日月', '明澈琉璃身', '法雨', '加持', '大愿般若船', '奇爱医生', '胜军', '轨道红移', '灭罪累生善', '禳灾', '愿印']|
丰饶火漆后面应该是奇物啊，现在依然是事件
