### ISSUE TITLE
[Feat]:有没有考虑适配新出的模拟宇宙7 

### ISSUE THREAD

**Issue by yyh11** [CHNZYX/Auto_Simulated_Universe#144]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

如题，模拟七不能自动呜呜

**Comment by Eric-Joker** [comment]
不能吗？我这貌似可以啊

**Comment by shawersky319** [comment]
模拟7难度5刷了一晚上了，没问题

**Comment by yyh11** [comment]
> 模拟7难度5刷了一晚上了，没问题

那可能是我的设备问题吧，我再去调设置试试

**Comment by nyano** [comment]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/5079651/b9747ba7-00b4-4587-bb1a-064e55cf68b8)
模拟宇宙7概率性地图无法识别，-1
典型是挂机一晚上，相比世界6所花费的次数直接少一半（当然练度也是原因之一）
已确认清晰度设置正确
