### ISSUE TITLE
[Feat]: 可以把事件选项和祝福选择的优先度放在配置文件里吗

### ISSUE THREAD

**Issue by yanmofeixi** [CHNZYX/Auto_Simulated_Universe#145]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

看着好多事件（比如银河好人（三））被白白跳过，有点影响效率。

要修改的话似乎只能改代码，如果放在一个外置的配置文件就好了

**Comment by baldwk** [comment]
info.yml里可以把祝福和事件的选项加进去，顺序就是优先级，但是没有黑名单机制，每次奇物选了银河大乐透必翻车，希望改善下
