### ISSUE TITLE
[Bug]: conda 环境的 check_req 方法存在异常

### ISSUE THREAD

**Issue by ZhReimu** [CHNZYX/Auto_Simulated_Universe#147]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v5.10 stable

### 重现步骤

1. 使用 `conda create -n testEnv` 之类的命令创建一个 conda 环境
2. 使用 `conda activate testEnv` 进入刚刚创建好的环境
3. 克隆本仓库代码或下载 release 的 sources
4. 执行 `pip install -r requirements.txt`
5. 执行 `python gui.py`
6. 按照流程校准、运行

### 期望的结果是什么？

正常开始自动化锄大地

### 实际的结果是什么？

提示 **未安装依赖库或环境变量未正确设置**

### 补充说明（可选）

问题出在这个方法的判定上
```python
    def check_req(self):
        self._stop = os.system('pip show numpy > NUL 2>&1') and not self.unlock
        if self._stop:
            log.info("未安装依赖库或环境变量未正确设置")
        time.sleep(10)
        self._stop = os.system('pip show numpy > NUL 2>&1') and not self.unlock
        if self._stop:
            log.info("未安装依赖库或环境变量未正确设置")
```
这里我觉得很奇怪, 如果没有安装 `numpy`, 在执行 **import numpy as np** 时就应该报错了的, 是不是没必要在这里再做一次判断, 或者换一种判断方式, 因为 conda 的环境变量是执行了 `conda activate envName` 之后才有的, 实测这里的 `os.system` 不会带上 conda 的环境变量, 如下图
为了方便触发, 在 `utils.py` 里加了段 `log.info(os.system('pip --version'))` 测试
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/58155247/e8d86afd-c47e-4d60-832b-99d20a1d9930)
这是我本机 base python 环境
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/58155247/c8d3da20-f43a-43f1-823d-7df2b87656b9)
这是 conda 的 python 环境
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/58155247/274a97ab-3790-4cf4-82bb-b00899076445)

**Comment by ZhReimu** [comment]
在修改了这个判断后一切正常了, 毕竟该装的库实际上都有了
```python
    def check_req(self):
        self._stop = os.system('echo pass > NUL 2>&1') and not self.unlock
        if self._stop:
            log.info("未安装依赖库或环境变量未正确设置")
        time.sleep(10)
        self._stop = os.system('echo pass > NUL 2>&1') and not self.unlock
        if self._stop:
            log.info("未安装依赖库或环境变量未正确设置")
```

**Comment by CHNZYX** [comment]
这个判定是给打包版gui用的。确实没有考虑虚拟环境conda。
