### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by XIKONGSAKET** [CHNZYX/Auto_Simulated_Universe#148]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.20

### 重现步骤

在卸载高版本python，装回3.8之后，手动完成了安装所有pip上的东西以后，即，手动安装了install_requirements指向的txt里面的所有库以后，点align那个，然后显示：

C:\Windows\System32>cd/d "D:\Auto_Simulated_Universe-main\"

D:\Auto_Simulated_Universe-main>python align_angle.py
Access is denied.

D:\Auto_Simulated_Universe-main>pause
Press any key to continue . . .
我确认我是用了管理员权限的。我的电脑是登着正版win11（买回来就是，我还没法刷，我在英国，自动更新只能暂停不能取消）
我已经每一个文件点开属性解除锁定了，试过把这个文件放在C盘，D盘，microsoft自动同步的网盘里，都被拒绝访问了。我的电脑登录着三个账户，一个是我个人的，没有microsoft存储空间，一个是系统默认的admin，还有一个英国的大学的学校微软账户，有网盘存储空间。我不知道该怎么办

### 期望的结果是什么？

期待打开崩铁能自动校准！

### 实际的结果是什么？

访问被拒绝

### 日志记录

C:\Windows\System32>cd/d "D:\Auto_Simulated_Universe-main\"

D:\Auto_Simulated_Universe-main>python align_angle.py
Access is denied.

D:\Auto_Simulated_Universe-main>pause
Press any key to continue . . .

**Comment by XIKONGSAKET** [comment]
管理员运行align_angle.py也会出现一下然后直接闪退。切到游戏并没有任何事情发生。用cmd运行：python align_angle.py 也会直接被deny。有人能说说这事什么情况吗

**Comment by XIKONGSAKET** [comment]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/142372363/bd99f1ba-7851-4143-89fa-13c65843e841)
这是我下回PY3.11后多次点击.py文件终于截图截到的内容，能不能看看到底为什么我的.py全都运行不了

**Comment by XIKONGSAKET** [comment]
费了半天劲解锁了超级系统权限以后，
numpy又出问题了。就是他明明装上了，但是调用的时候又没有。
Microsoft Windows [版本 10.0.19045.3324]
(c) Microsoft Corporation。保留所有权利。

C:\Users\ASUS>pip install numpy
Requirement already satisfied: numpy in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.25.2)

C:\Users\ASUS>pip install numpy
Requirement already satisfied: numpy in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.25.2)

C:\Users\ASUS>pip list
Package                   Version
------------------------- ------------
altgraph                  0.17.3
anyio                     3.7.1
certifi                   2023.7.22
charset-normalizer        3.2.0
colorama                  0.4.6
coloredlogs               15.0.1
copier                    8.1.0
decorator                 5.1.1
dunamai                   1.18.0
flatbuffers               23.5.26
flet                      0.9.0
flet-core                 0.9.0
flet-runtime              0.9.0
funcy                     2.0
h11                       0.14.0
httpcore                  0.17.3
httpx                     0.24.1
humanfriendly             10.0
idna                      3.4
Jinja2                    3.1.2
jinja2-ansible-filters    1.3.2
keyboard                  0.13.5
MarkupSafe                2.1.3
MouseInfo                 0.1.3
mpmath                    1.3.0
numpy                     1.25.2
oauthlib                  3.2.2
onnxruntime               1.15.1
opencv-python             4.8.0.76
packaging                 23.1
pathspec                  0.11.2
pefile                    2023.2.7
Pillow                    10.0.0
plumbum                   1.8.2
ppocr-onnx                0.0.3.9
prompt-toolkit            3.0.36
protobuf                  4.24.0
PyAutoGUI                 0.9.54
pyclipper                 1.3.0.post4
pydantic                  1.10.12
PyGetWindow               0.0.9
Pygments                  2.16.1
pyinstaller               5.13.0
pyinstaller-hooks-contrib 2023.6
PyMsgBox                  1.0.9
pyperclip                 1.8.2
pypng                     0.20220715.0
pyreadline3               3.4.1
PyRect                    0.2.0
PyScreeze                 0.1.28
pystray                   0.19.4
pytweening                1.0.7
pytz                      2023.3
pyuac                     0.0.3
pywin32                   306
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
pyyaml-include            1.3.1
qrcode                    7.4.2
questionary               2.0.0
repath                    0.9.0
requests                  2.31.0
shapely                   2.0.1
six                       1.16.0
sniffio                   1.3.0
sympy                     1.12
tee                       0.0.3
typing_extensions         4.7.1
tzdata                    2023.3
tzlocal                   5.0.1
urllib3                   2.0.4
watchdog                  3.0.0
wcwidth                   0.2.6
websocket-client          1.6.1
websockets                11.0.3
winotify                  1.1.0

C:\Users\ASUS>python --version
Python 3.11.4

C:\Users\ASUS>
C:\Users\ASUS>cd /d F:\STARRAILS\Auto_Simulated_Universe-5.20

F:\STARRAILS\Auto_Simulated_Universe-5.20>python align_angle.py
Traceback (most recent call last):
  File "F:\STARRAILS\Auto_Simulated_Universe-5.20\align_angle.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

F:\STARRAILS\Auto_Simulated_Universe-5.20>

**Comment by CHNZYX** [comment]
确保环境变量正确配置。实在不行我建议你卸载干净python，然后网上搜教程装一个anaconda

**Comment by XIKONGSAKET** [comment]
作者要不要在说明文档说一下，强烈不建议大家去microsoft商店下python，它会被塞进操作不了的地方。去官网下载然后默认安装就会装在至少可以操作的地方。
我卸载了python，去官网重装了。垃圾microsoft商店。

**Comment by nyano** [comment]
> 作者要不要在说明文档说一下，强烈不建议大家去microsoft商店下python，它会被塞进操作不了的地方。去官网下载然后默认安装就会装在至少可以操作的地方。 我卸载了python，去官网重装了。垃圾microsoft商店。

1.商店的python就是个笑话，主要可以自动更新。但是日常使用时其实一般用的是虚拟环境，当然你不会的话，所以还是官网下更方便
2.ModuleNotFoundError: No module named 'numpy'   也许是库版本问题？
3. info.yml不是utf-8格式，你可以用notepad打开，然后手动另存为以utf-8覆盖保存。但更建议把文件夹全删了重新下载副本
4. 权限问题，建议手动用管理员权限打开cmd，然后再运行脚本。如果是管理员，标题栏有管理员三个字。powershell同理，打开后多输一步cmd即可。你当前账户是管理员不代表你这个cmd进程是管理员，还有UAC呢
5. 当然，商店版python 即使管理员对文件夹操作也挺难的，这种基本上给你个自动更新的版本，然后是让你用来搞虚拟环境的，不是让你直接对商店版文件进行操作的
