### ISSUE TITLE
[Bug]: 没有正确识别配置文件的奇物优先级

### ISSUE THREAD

**Issue by bin1129** [CHNZYX/Auto_Simulated_Universe#149]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.21

### 重现步骤

作者，我上次提交过这个奇物优先级bug，你回复说是修复了，但我刚刚试了下最新的还是没修复，可能你没理解，我在ocr.py最后一行log出了self.strange和self.prior_bless，前者本来是奇物优先级，但除了火漆以外都错误地被事件替换了，导致奇物优先级失效

### 期望的结果是什么？

正确识别配置文件的奇物优先级

### 实际的结果是什么？

奇物优先级错误地被事件优先级替换

### 日志记录

INFO [2023-08-17 10:42:52,125] [ocr.py:142] self.strange|['巡猎火漆', '购买1个星祝福', '跳上右边的砖块', '丢下雕像', '和序列扑满玩', '信仰星神', '克里珀的恩赐', '哈克的藏品', '动作片', '感恩克里珀星神']|self.prior_bless|['火堆外的夜', '柘弓危矢', '射不主皮', '帝星君临', '白矢决射御', '云镝逐步离', '彤弓素矰', '背孤击虚']|

**Comment by CHNZYX** [comment]
更新到最新版本，重新覆盖info.yml

**Comment by CHNZYX** [comment]
已经修复，感谢提出bug
