### ISSUE TITLE
[Bug]: 更新到新版本后进入BOSS房会边跑边释放E，导致跑过了BOSS找不到目标直接退出模拟宇宙

### ISSUE THREAD

**Issue by akariiowo** [CHNZYX/Auto_Simulated_Universe#153]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.20

### 重现步骤

进入boss房

### 期望的结果是什么？

进入BOSS房先放完战技，再往前走攻击boss进入战斗

### 实际的结果是什么？

进入BOSS房会等到跑到BOSS脸上才开始放战技，边跑边切换角色放战技导致攻击目标丢失，放完四个E技能会A空气。最后直接退出。

### 补充说明（可选）

环境是从5.08版本运行update.bat更新的，2023年8月19日更新。

**Comment by CHNZYX** [comment]
好的，下次更新会尝试修复
