### ISSUE TITLE
新版本会在黑塔办公室乱走不进模拟宇宙

### ISSUE THREAD

**Issue by kuronekoda** [CHNZYX/Auto_Simulated_Universe#158]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.20

### 重现步骤

在黑塔办公室会一直乱走不进模拟宇宙，手动进入模拟宇宙进图后会打开地图或者打开设置不知道在干嘛，打完小怪后在入口徘徊按普通不进入下一关

### 期望的结果是什么？

能够正常识别黑塔办公室及模拟宇宙地图

### 实际的结果是什么？

.

**Comment by CHNZYX** [comment]
请更新到5.30
