### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by JunNanLYS** [CHNZYX/Auto_Simulated_Universe#160]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

是否可以改进获取角色角度的方法`align_angle.py下的get_angle`，该方法是将一定范围内的蓝色给保留下来其余部分涂黑，但是在遇到一些蓝色的东西例如：拟造花萼、传送点等，会出现获取角色坐标错误。

可以使用HSV来保留一定范围内的颜色，效果如下。

改变前
<img width="227" alt="before" src="https://github.com/CHNZYX/Auto_Simulated_Universe/assets/101338312/206e4486-0127-4306-bca1-0531c6029192">
改变后
<img width="227" alt="after" src="https://github.com/CHNZYX/Auto_Simulated_Universe/assets/101338312/5a637f1d-c284-4aa7-9359-7e7848efd0b0">

我目前已经有修改好的代码

**Comment by CHNZYX** [comment]
可以，感谢改进
