### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aligardo-AR** [CHNZYX/Auto_Simulated_Universe#162]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.30

### 重现步骤

运行模拟宇宙第七世界，因地图选择有概率出现：迷路，不与事件交互

### 期望的结果是什么？

解决上述问题

### 实际的结果是什么？

解决上述问题

### 日志记录

INFO [2023-09-01 01:21:55,579] [states.py:288] 地图-1已完成,相似度-1,进入11层
INFO [2023-09-01 01:21:56,585] [utils.py:589] 交互点相似度0.972444474697113，位置104,172
INFO [2023-09-01 01:21:59,364] [utils.py:589] 交互点相似度0.8884926438331604，位置108,159
INFO [2023-09-01 01:22:44,231] [utils.py:27] 通知：地图-1，当前层数:11  暂离
ERROR [2023-09-01 01:22:44,232] [states.py:413] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-09-01 01:22:44,713] [utils.py:276] 匹配到图片 ./imgs/setting.jpg 相似度 0.994321 阈值 0.980000
INFO [2023-09-01 01:22:51,467] [utils.py:276] 匹配到图片 ./imgs/yes.jpg 相似度 0.998938 阈值 0.970000
INFO [2023-09-01 01:22:56,345] [utils.py:276] 匹配到图片 ./imgs/floor/ff11.jpg 相似度 0.991880 阈值 0.970000
INFO [2023-09-01 01:22:56,345] [utils.py:539] 当前层数：11
INFO [2023-09-01 01:22:58,291] [utils.py:589] 交互点相似度0.963312029838562，位置104,174
INFO [2023-09-01 01:23:01,143] [utils.py:589] 交互点相似度0.8961468935012817，位置108,159
INFO [2023-09-01 01:23:46,030] [utils.py:27] 通知：地图-1，当前层数:11  暂离
ERROR [2023-09-01 01:23:46,030] [states.py:413] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-09-01 01:23:46,525] [utils.py:276] 匹配到图片 ./imgs/setting.jpg 相似度 0.994401 阈值 0.980000
INFO [2023-09-01 01:23:53,358] [utils.py:276] 匹配到图片 ./imgs/yes.jpg 相似度 0.998938 阈值 0.970000
WARNING [2023-09-01 01:24:16,298] [states.py:136] 等待游戏窗口

### 补充说明（可选）

不点事件，可以看出来在这里青雀是A了一下。后面就是在地图瞎逛了，然后就脱离卡死了，可以对应上面的log
![20786066AD1AB6EC7C1BD6A4BE07AC6F](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/143745043/4c399d59-b9ce-4f46-b5e7-1c57606cb190)

**Comment by CHNZYX** [comment]
能否提供完整的屏幕截图？

**Comment by fjf010223** [comment]
我之前提的BUG跟这个一样，只要是这种直接显示贴图的事件/遭遇层，就会卡主然后无限脱离卡死
![180a087ce7af2720778d813f308edb44](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/24584711/15712ea1-bfbd-45fe-b447-a82af1d9b510)
![cdb51929e4f66ca5cb71f3103444e782](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/24584711/77629ea5-e644-4ae8-8fac-6e9caa1f850a)

**Comment by Aligardo-AR** [comment]
现在脚本打不开截图有用吗？

**Comment by JunNanLYS** [comment]
这个图我也遇到过，确实是会迷路，不过事件长这样，不过我只有进入事件的截图(是我自己手操进的事件)
<img width="962" alt="屏幕截图 2023-08-31 184053" src="https://github.com/CHNZYX/Auto_Simulated_Universe/assets/101338312/61b120c4-4493-4c7d-8106-26328833e92a">

**Comment by Aligardo-AR** [comment]
> 能否提供完整的屏幕截图？
![WT9FJA)EI@{W{W1R4H`Z07](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/143745043/e08901a5-edf6-46c7-9307-75b2bbe8a72f)

INFO [2023-09-03 15:35:10,941] [utils.py:975] 进入新地图或者进入战斗 6.950378054612624
INFO [2023-09-03 15:35:11,446] [utils.py:276] 匹配到图片 ./imgs/f.jpg 相似度 0.995149 阈值 0.955000
INFO [2023-09-03 15:35:11,461] [utils.py:1009] removed:((47.25714285714286, 139.68571428571428), 3)
INFO [2023-09-03 15:35:11,531] [utils.py:276] 匹配到图片 ./imgs/f.jpg 相似度 0.995149 阈值 0.970000
INFO [2023-09-03 15:35:12,045] [utils.py:276] 匹配到图片 ./imgs/f.jpg 相似度 0.995149 阈值 0.970000
INFO [2023-09-03 15:35:12,057] [states.py:275] 识别到传送点
INFO [2023-09-03 15:35:13,363] [states.py:287] 地图56417已完成,相似度0.6026315789473684,进入2层
INFO [2023-09-03 15:35:13,899] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:35:14,577] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:35:15,825] [utils.py:593] 交互点相似度0.9237123131752014，位置141,84
INFO [2023-09-03 15:35:18,803] [utils.py:593] 交互点相似度0.8826587200164795，位置129,98
INFO [2023-09-03 15:36:05,112] [utils.py:27] 通知：地图-1，当前层数:2  暂离
ERROR [2023-09-03 15:36:05,134] [states.py:412] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-09-03 15:36:05,743] [utils.py:276] 匹配到图片 ./imgs/setting.jpg 相似度 0.993281 阈值 0.980000
INFO [2023-09-03 15:36:12,498] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:13,107] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:13,735] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:14,761] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:15,449] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:16,104] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:17,110] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:17,735] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:18,445] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:19,492] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:20,191] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:20,803] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:21,804] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:22,436] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:23,051] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:24,052] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:24,667] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:25,270] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:26,325] [utils.py:276] 匹配到图片 ./imgs/setting.jpg 相似度 0.993277 阈值 0.980000
INFO [2023-09-03 15:36:33,085] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:33,681] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:34,292] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:35,301] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:35,917] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:36,522] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:37,523] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:38,145] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:38,755] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:39,794] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:40,421] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:41,018] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:42,031] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:42,648] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:43,263] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:44,277] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:44,885] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:45,506] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:46,469] [utils.py:276] 匹配到图片 ./imgs/yes.jpg 相似度 0.998938 阈值 0.970000
INFO [2023-09-03 15:36:47,399] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 15:36:52,015] [utils.py:276] 匹配到图片 ./imgs/floor/ff2.jpg 相似度 0.985972 阈值 0.955000
INFO [2023-09-03 15:36:52,016] [utils.py:543] 当前层数：2
INFO [2023-09-03 15:36:54,075] [utils.py:593] 交互点相似度0.9491814374923706，位置142,84
INFO [2023-09-03 15:36:57,482] [utils.py:593] 交互点相似度0.8891744613647461，位置124,103
