### ISSUE TITLE
[Bug]: 版本下限是5.32但是release里为5.31

### ISSUE THREAD

**Issue by f59375543** [CHNZYX/Auto_Simulated_Universe#167]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.31

### 重现步骤

release版本对不上

### 期望的结果是什么？

能够正常启动

### 实际的结果是什么？

INFO [2023-09-01 23:32:29,528] [states.py:35] 当前版本：v5.31 beta  当前命途：巡猎
INFO [2023-09-01 23:32:31,087] [states.py:39] 版本下限：v5.32
INFO [2023-09-01 23:32:31,088] [states.py:50] 当前版本过低，强制退出
INFO [2023-09-01 23:32:31,089] [utils.py:27] 通知：初始计数：0  开始运行
INFO [2023-09-01 23:32:31,090] [states.py:89] 加载地图
INFO [2023-09-01 23:32:31,299] [states.py:95] 加载地图完成，共 65 张
INFO [2023-09-01 23:32:31,312] [utils.py:27] 通知：   已退出自动化

**Comment by f59375543** [comment]
内置更新器也无法更新

![20230901233543](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/43315911/b1b8ffd4-826e-413c-9051-fd96f1c59574)

**Comment by ze-xi** [comment]
+1，同样的问题

**Comment by alvinzw** [comment]
确实，昨天下午开始的这个问题

**Comment by olllon1** [comment]
也是这个问题

**Comment by A359003** [comment]
+1，release也有写，怎么辉石呢？

**Comment by Azarasi2000** [comment]
可否不要設定版本下限
