### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aligardo-AR** [CHNZYX/Auto_Simulated_Universe#169]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.3.2

### 重现步骤

世界7，休整地图，进入以后迷路，不找黑塔，也不去下一层

### 期望的结果是什么？

解决bug

### 实际的结果是什么？

解决bug

### 日志记录

INFO [2023-09-03 14:36:43,388] [states.py:287] 地图-1已完成,相似度-1,进入6层
INFO [2023-09-03 14:36:43,863] [utils.py:276] 匹配到图片 ./imgs/yes.jpg 相似度 0.998938 阈值 0.970000
INFO [2023-09-03 14:36:44,772] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:45,396] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:45,990] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:47,034] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:47,641] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:48,255] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:49,311] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:49,916] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:50,610] [states.py:558] 匹配不到任何图标
INFO [2023-09-03 14:36:54,440] [states.py:345] 地图编号：78620  相似度：0.3028322440087146
INFO [2023-09-03 14:36:54,440] [utils.py:27] 通知：疑似在黑塔办公室  相似度过低
地图文件： imgs/maps/78620/map_4036_4062_.jpg
INFO [2023-09-03 14:36:54,644] [states.py:375] target {((12.529411764705882, 34.294117647058826), 3), ((23.853658536585368, 36.90243902439025), 1)}
INFO [2023-09-03 14:37:03,544] [utils.py:276] 匹配到图片 ./imgs/f.jpg 相似度 0.995152 阈值 0.970000
INFO [2023-09-03 14:37:10,390] [utils.py:975] 进入新地图或者进入战斗 25.619765755808743
INFO [2023-09-03 14:37:19,490] [utils.py:975] 进入新地图或者进入战斗 8.178300098703982

### 补充说明（可选）

![QQ截图20230903144206](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/143745043/54dc21af-3cf9-4840-9ebb-95749977a242)

**Comment by CHNZYX** [comment]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/30075174/8b647785-633a-4307-92e2-2f8717bca1a9)
请把这一块遮挡物（包括小红点）清理干净

**Comment by Aligardo-AR** [comment]
好的！
