### ISSUE TITLE
丢弃奇物事件卡住

### ISSUE THREAD

**Issue by SonoTokan** [CHNZYX/Auto_Simulated_Universe#17]
在这个事件无限卡住。
虽然不知道为什么进入这个事件，但是考虑到程序的健壮性，建议加入丢弃奇物事件的识别。
![pic_honkai](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/40739351/fedc2c90-0c26-49c1-b5f4-cd0a5678f24f)

**Comment by CHNZYX** [comment]
是否更新到了最新版本？这个bug已经修复了

**Comment by SonoTokan** [comment]
谢谢，上周发现的bug，抱歉滞后了。
