### ISSUE TITLE
[Bug]: info.yml的阵容配队配置未生效

### ISSUE THREAD

**Issue by Kethers** [CHNZYX/Auto_Simulated_Universe#175]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.3.3

### 重现步骤

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/49612587/c9e1497a-7890-4bd3-9318-82783d400ab3)
按照README更改info.yml的order_text后，实际配队并不生效，使用的是游戏中当前模拟宇宙上次存档使用的阵容。

### 期望的结果是什么？

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/49612587/a38f4e8e-100c-42f0-ad85-2edb1cdd08a4)
期望的配队顺序是：白鹭 克拉拉 杰帕德 景元

### 实际的结果是什么？

实际使用的是游戏存档的阵容。

**Comment by Rasput1n00** [comment]
这个问题一直都有，但是并不影响使用啊，你拿你想用的阵容先进一次模拟宇宙退出就行了。BTW，第一位最好是远程攻击的。

**Comment by Klamist** [comment]
这个功能直接忽略就行……你直接选你要的角色，然后就在选完的界面开始运行。
