### ISSUE TITLE
[Bug]: 运行后异常退出

### ISSUE THREAD

**Issue by bin1129** [CHNZYX/Auto_Simulated_Universe#176]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.33

### 重现步骤

昨晚因为代码版无法运行，只能用作者打包好的刷，睡觉刷了几个小时没出问题，中午看见代码更新了下了代码版的，运行到第二层异常退出，然后全部删了用全新的依然异常退出，昨晚运行地好好的打包版没任何改动也异常退出，校准、更新依赖、重启电脑全都没用，日志也看不出问题，另外前几天卡倒数第二层黑塔强化无限循环的那个版本依然正常运行不会异常退出

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

异常退出

### 日志记录

WARNING [2023-09-06 13:14:12,082] [utils.py:93] 等待游戏窗口
INFO [2023-09-06 13:14:12,083] [utils.py:125] DPI: 1.25 A:1.0
INFO [2023-09-06 13:14:12,083] [utils.py:128] TEXT: 崩坏：星穹铁道
INFO [2023-09-06 13:14:13,084] [states.py:41] 当前版本：v5.33 beta  当前命途：巡猎
INFO [2023-09-06 13:14:13,918] [states.py:53] 版本下限：v5.31
INFO [2023-09-06 13:14:14,008] [utils.py:28] 通知：初始计数：0  开始运行
INFO [2023-09-06 13:14:14,009] [states.py:108] 加载地图
INFO [2023-09-06 13:14:14,491] [states.py:114] 加载地图完成，共 66 张
INFO [2023-09-06 13:14:14,678] [utils.py:293] 匹配到图片 ./imgs/f.jpg 相似度 0.995153 阈值 0.970000
INFO [2023-09-06 13:14:15,150] [utils.py:293] 匹配到图片 ./imgs/f.jpg 相似度 0.995153 阈值 0.970000
INFO [2023-09-06 13:14:15,659] [states.py:193] 停止运行
INFO [2023-09-06 13:14:15,661] [utils.py:28] 通知：   已退出自动化

**Comment by CHNZYX** [comment]
可能更新了错误版本，导致被永久禁用了。目前的解决方案只有换一台电脑了（或者重装系统）。如果接受不了可以联系我qq：3501801665
