### ISSUE TITLE
[Bug]: ImportError: cannot import name 'isrun' from 'utils.mylib'

### ISSUE THREAD

**Issue by xuanqingyi** [CHNZYX/Auto_Simulated_Universe#180]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v5.34 beta

### 重现步骤

D:\崩坏\模拟宇宙\Auto_Simulated_Universe-main>cd/d "D:\崩坏\模拟宇宙\AUTO_S~1\"

D:\崩坏\模拟宇宙\AUTO_S~1>python states.py --find=1
Traceback (most recent call last):
  File "D:\崩坏\模拟宇宙\AUTO_S~1\utils\utils.py", line 24, in <module>
    from mylib import isrun
ModuleNotFoundError: No module named 'mylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\崩坏\模拟宇宙\AUTO_S~1\states.py", line 15, in <module>
    from utils.utils import UniverseUtils, set_forground, notif
  File "D:\崩坏\模拟宇宙\AUTO_S~1\utils\utils.py", line 26, in <module>
    from utils.mylib import isrun
ImportError: cannot import name 'isrun' from 'utils.mylib' (D:\崩坏\模拟宇宙\AUTO_S~1\utils\mylib\__init__.py)

### 期望的结果是什么？

前几天还好用，后来重新下载 更新 都报错，gui也打不开了

### 实际的结果是什么？

前几天还好用，后来重新下载 更新 都报错，gui也打不开了

### 日志记录

无

### 补充说明（可选）

无

**Comment by Eisaichen** [comment]
same here, 5.33 has the same problem, downgrade to 5.32 fixed the issue.

**Comment by XIKONGSAKET** [comment]
我也一样！

**Comment by XIKONGSAKET** [comment]
5.4beta未解决该问题

**Comment by Zyz9999** [comment]
yeah.
The file 'isrun.py' in the folder 'mylib' is not present,was it forgotten?

**Comment by CHNZYX** [comment]
已经解决，抱歉疏漏了
