### ISSUE TITLE
[Feat]: 开局选项与最优先祝福写入info.yml

### ISSUE THREAD

**Issue by ayssia** [CHNZYX/Auto_Simulated_Universe#183]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

目前有1个最优先祝福（火堆外的夜）是写死在ocr.py里的，是否可以增加相关代码使之可以在info.yml中自定义？

另外开局3选1选项目前无法自定义选择（总是会点击中间那个），希望也可以类似祝福一样添加自定义选择的可能。

**Comment by CHNZYX** [comment]
暂时没有实现这些功能的必要，如果你打算提供可以pr
