### ISSUE TITLE
[Feat]: 搞下热键自定义吧。。。

### ISSUE THREAD

**Issue by Eric-Joker** [CHNZYX/Auto_Simulated_Universe#184]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

我玩mc玩多了比f键更习惯点e，所以把交互点改成e了。
之前一直自己改源码用，前几天源码中还加了点pyc，啧，虽然不是不能反，但是好麻烦啊

**Comment by Klamist** [comment]
我也是全E键。
但现在自己改press('e')再换一下E.jpg不能用了吗？

**Comment by CHNZYX** [comment]
不会支持。目前f键交互点判断用的是图片匹配的逻辑，如果自定义热键就需要数十张图片模板，因此不会考虑。

**Comment by CHNZYX** [comment]
一个折中的解决方案是维持游戏的默认按键，打游戏的时候就开键盘映射

**Comment by Eric-Joker** [comment]
> 我也是全E键。 但现在自己改press('e')再换一下E.jpg不能用了吗？

应该是因为防盗卖源码里加了点pyc没源码，这里还有点press('f')得改。

**Comment by Eric-Joker** [comment]
> 不会支持。目前f键交互点判断用的是图片匹配的逻辑，如果自定义热键就需要数十张图片模板，因此不会考虑。

生成图片可以嘛，差不多就是一个背景上面写个e或者f，没有噪点也能正常识别。我明天研究下pr？

**Comment by Eric-Joker** [comment]
> 一个折中的解决方案是维持游戏的默认按键，打游戏的时候就开键盘映射

主要是我反编3.7的那个文件在3.11上用出来个bug，不知道反编之前有没有，第二层就不操控角色移动了。以前好像就算map里没有的图也会尝试追踪到交互点，现在压根不动了

**Comment by CHNZYX** [comment]
如果只改f且你能生成可识别的图片，那我可以配合你更改。不过这个功能只会在源码版中支持，不会写入配置文件（info）

**Comment by Eric-Joker** [comment]
> 如果只改f且你能生成可识别的图片，那我可以配合你更改。不过这个功能只会在源码版中支持，不会写入配置文件（info）

嘛，我还寻思试着写个完善的功能尽可能适配这个自定义热键呢（

**Comment by Eric-Joker** [comment]
> 如果只改f且你能生成可识别的图片，那我可以配合你更改。不过这个功能只会在源码版中支持，不会写入配置文件（info）

嘛，我还寻思写个完善的功能呢。不加配置文件的话在哪添加生成图片的逻辑呢，还是说就给我们这种有特殊要求的单拿个程序生成图片

**Comment by CHNZYX** [comment]
不会在配置文件，但会在代码里。你只需要pr生成图片的函数
