### ISSUE TITLE
5.4版本运行一会会自动停止

### ISSUE THREAD

**Issue by jelly0925** [CHNZYX/Auto_Simulated_Universe#186]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

Auto_Simulated_Universe_v5.4

### 重现步骤

Auto_Simulated_Universe_v5.4 自动运行大概5次后，会自动停止任务，需要两次点击运行

### 期望的结果是什么？

应该一直执行

### 实际的结果是什么？

自动停止

**Comment by CHNZYX** [comment]
是否已经刷满34次？如果刷满可以打开调试模式

**Comment by jelly0925** [comment]
> 是否已经刷满34次？如果刷满可以打开调试模式

没有呀，刚开始刷就这样了，我打开调试模式看一下日志

**Comment by sunlcy** [comment]
我也遇到一次  提示什么什么函数发生运行时错误 退出自动化  log里没有 我也没截图

**Comment by CHNZYX** [comment]
已修复，请更新到最新版本
