### ISSUE TITLE
[Bug]:第三世界空间站转圈圈 

### ISSUE THREAD

**Issue by MicroDust-real** [CHNZYX/Auto_Simulated_Universe#191]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.4

### 重现步骤

[ERROR] [2023-09-12 15:36:12,346] 地图23480未发现目标,相似度0.29831932773109243，尝试暂离

### 期望的结果是什么？

顺利进门

### 实际的结果是什么？

跑到门前之后  A两下 (但是够不到门) 
然后180度转头跑回去 就开始无限撞墙

**Comment by CHNZYX** [comment]
试试最新版本
