### ISSUE TITLE
自动完一次第五世界，然后在我没有任何操作的情况下就切到第七世界打

### ISSUE THREAD

**Issue by XIKONGSAKET** [CHNZYX/Auto_Simulated_Universe#194]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.4 stable

### 重现步骤

就正常启动。我手动打了一遍5，然后再开脚本

### 期望的结果是什么？

按作者说的，按照上一个完成过的宇宙打。

### 实际的结果是什么？

打完一遍五就自动划到第七宇宙去打了，今天早上醒来我甚至看见它在寰宇蝗灾里面卡着说匹配不到图像。而且我的一号位已经放了驭空，按作者要求的成女远程角色，但是切到第七宇宙我是没有队伍能在脚本的选buff下稳定过还包含一个成女角色的队伍的，我实在是绷不住啦

### 日志记录

[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/12589272/log.txt)

**Comment by XIKONGSAKET** [comment]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/142372363/29c7042c-f19d-4c07-8e10-9e875e5982ea)
就这个图，他还会一直卡住在这个平台的左前角，疯狂普攻
明明前面有个事件他就不过去

**Comment by XIKONGSAKET** [comment]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/142372363/54305351-a64a-4d5c-9ba4-342be01489bf)
停云也是，驭空也是，老在这！

**Comment by Shawnsmithzheng** [comment]
你可以尝试重新校准一次，这可能可以解决你的问题

**Comment by XIKONGSAKET** [comment]
我当然重新校准了，但是问题依然存在。

**Comment by XIKONGSAKET** [comment]
[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/12596682/log.txt)
这是卡在上面那个图的地方不停普攻的log

**Comment by CHNZYX** [comment]
试试最新版本
