### ISSUE TITLE
安装依赖库报错

### ISSUE THREAD

**Issue by Guoyh1212** [CHNZYX/Auto_Simulated_Universe#2]
安装win32gui依赖库时报错ModuleNotFoundError: No module named 'win32.distutils.command'，尝试手动安装过pywin32，仍然解决不了。
![QQ图片20230519235445](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/93355016/bcc79d9f-dcfb-4042-9980-273787b649fb)

**Comment by river0Love** [comment]
pip install pypiwin32

**Comment by Guoyh1212** [comment]
pypwin32也装了，你看最上面
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/93355016/ee1c091b-6ccb-4fb3-9e98-dfaae5eb0310)

**Comment by CHNZYX** [comment]
更新requirements.txt后已解决
