### ISSUE TITLE
[Bug]: 'SimulatedUniverse' object has no attribute 'runkey'

### ISSUE THREAD

**Issue by Eisaichen** [CHNZYX/Auto_Simulated_Universe#203]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v5.8 8c391d0

### 重现步骤

下载v5.8源码包
使用
python .\gui.py
运行

开始自动化后，第一层正常，但已进入第二层就会报错
试过启用/禁用速通模式，都会报错

### 期望的结果是什么？

Run as designed.

### 实际的结果是什么？

Throw exception.

### 日志记录

INFO [2023-09-17 23:05:03,413] [utils.py:700] 地图45516已完成,相似度0.9,进入2层

E: 运行函数时出现错误
Traceback (most recent call last):
  File "D:\Application\Auto_Simulated_Universe\gui\choose.py", line 31, in run
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Application\Auto_Simulated_Universe\states.py", line 893, in start
    self.route()
  File "D:\Application\Auto_Simulated_Universe\states.py", line 181, in route
    res = self.normal()
          ^^^^^^^^^^^^^
  File "D:\Application\Auto_Simulated_Universe\states.py", line 517, in normal
    get_direc_only_minimap(self)
  File "mylib.py", line 134, in get_direc_only_minimap
AttributeError: 'SimulatedUniverse' object has no attribute 'runkey'
INFO [2023-09-17 23:05:06,775] [states.py:833] 尝试停止运行
INFO [2023-09-17 23:05:06,777] [utils.py:36] 通知：   已退出自动化

(Auto_Simulated_Universe) PS D:\Application\Auto_Simulated_Universe>

**Comment by CHNZYX** [comment]
5.8源码包有问题，建议直接下载最新源码或者直接clone或pull
