### ISSUE TITLE
[Bug]: 打开调试模式情况下, 12层无法进入下一层, 并暂离

### ISSUE THREAD

**Issue by blangero** [CHNZYX/Auto_Simulated_Universe#207]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.7

### 重现步骤

正常使用, 精度1.4, 其他设置按照文档推荐设置.

### 期望的结果是什么？

今天的使用中, 共进入12层9次, 期待进入13层9次

### 实际的结果是什么？

共进入12层9次, 进入13层6次.

### 日志记录

INFO [2023-09-19 13:42:43,600] [utils.py:33] 通知：地图-1，当前层数:12  暂离
ERROR [2023-09-19 13:42:43,601] [states.py:502] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-09-19 13:42:44,044] [utils.py:316] 匹配到图片 ./imgs/setting.jpg 相似度 0.989679 阈值 0.980000
DEBUG [2023-09-19 13:42:49,825] [predict_system.py:94] dt_boxes num : 28, elapse : 0.3038804531097412
DEBUG [2023-09-19 13:42:49,907] [predict_system.py:110] rec_res num  : 28, elapse : 0.07532048225402832
DEBUG [2023-09-19 13:42:52,126] [predict_system.py:94] dt_boxes num : 32, elapse : 0.29460692405700684
DEBUG [2023-09-19 13:42:52,214] [predict_system.py:110] rec_res num  : 32, elapse : 0.08141589164733887
INFO [2023-09-19 13:42:53,170] [utils.py:316] 匹配到图片 ./imgs/yes1.jpg 相似度 0.998675 阈值 0.970000
INFO [2023-09-19 13:42:54,040] [utils.py:316] 匹配到图片 ./imgs/run.jpg 相似度 0.966979 阈值 0.940000
DEBUG [2023-09-19 13:42:55,200] [utils.py:169] 按下按钮 m，等待 0.2 秒后释放
INFO [2023-09-19 13:42:58,188] [utils.py:316] 匹配到图片 ./imgs/floor/ff12.jpg 相似度 0.981669 阈值 0.970000
INFO [2023-09-19 13:42:58,188] [utils.py:565] 当前层数：12
DEBUG [2023-09-19 13:42:58,188] [utils.py:169] 按下按钮 m，等待 0.2 秒后释放
DEBUG [2023-09-19 13:42:59,780] [utils.py:169] 按下按钮 1，等待 0 秒后释放
DEBUG [2023-09-19 13:43:00,536] [utils.py:169] 按下按钮 w，等待 0.55 秒后释放
DEBUG [2023-09-19 13:43:02,058] [utils.py:169] 按下按钮 w，等待 0 秒后释放
INFO [2023-09-19 13:43:02,966] [utils.py:626] 黑塔相似度0.8915868401527405，位置144,102
INFO [2023-09-19 13:43:04,219] [utils.py:626] 黑塔相似度0.833198070526123，位置149,105
INFO [2023-09-19 13:43:06,581] [utils.py:316] 匹配到图片 ./imgs/f.jpg 相似度 0.993222 阈值 0.970000
DEBUG [2023-09-19 13:43:06,587] [utils.py:169] 按下按钮 f，等待 0 秒后释放
INFO [2023-09-19 13:43:06,796] [mylib.py:155] need_confirm 黑塔
DEBUG [2023-09-19 13:43:07,791] [utils.py:169] 按下按钮 esc，等待 0 秒后释放
INFO [2023-09-19 13:43:09,186] [utils.py:316] 匹配到图片 ./imgs/event.jpg 相似度 0.971498 阈值 0.970000
INFO [2023-09-19 13:43:11,148] [utils.py:316] 匹配到图片 ./imgs/arrow_1.jpg 相似度 0.996989 阈值 0.970000
DEBUG [2023-09-19 13:43:12,068] [utils.py:169] 按下按钮 esc，等待 0 秒后释放
INFO [2023-09-19 13:43:13,479] [utils.py:316] 匹配到图片 ./imgs/run.jpg 相似度 0.946545 阈值 0.940000
DEBUG [2023-09-19 13:43:13,876] [utils.py:169] 按下按钮 w，等待 0.3 秒后释放
DEBUG [2023-09-19 13:43:17,397] [utils.py:169] 按下按钮 esc，等待 0 秒后释放
INFO [2023-09-19 13:43:19,626] [utils.py:33] 通知：计数:12 已使用：0小时44分钟  平均22分钟一次  预计剩余8小时11分钟  已完成
INFO [2023-09-19 13:43:20,067] [states.py:495] 通关！当前层数:1

### 补充说明（可选）

之前有个issue里, 作者有提到 开启调试模式之后不会离开12层, 但是没有生效.

**Comment by CHNZYX** [comment]
谢谢，已经修复
