### ISSUE TITLE
[Bug]: 感谢作者提供的多用户后台运行思路，但是部署时有点小问题

### ISSUE THREAD

**Issue by f59375543** [CHNZYX/Auto_Simulated_Universe#208]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.8

### 重现步骤

在多用户部署后，游戏设置和外面完全一致，但是程序却在不断尝试暂离

### 期望的结果是什么？

能够正常运作

### 实际的结果是什么？

运作失败

### 日志记录

[log_2023-09-19-19-56.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/12662336/log_2023-09-19-19-56.txt)

**Comment by f59375543** [comment]
还有补充一点，就是启动以后，停止脚本失效，我连按多次停止按钮，命令行显示正在停止运作，但是还是没停下来，继续和我抢鼠标
![20230919230505](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/43315911/38a164e8-ea13-4db4-ab1c-6a51c60d4e46)

**Comment by CHNZYX** [comment]
请发送log.txt或命令行截图

**Comment by f59375543** [comment]
> 请发送log.txt或命令行截图

[log_2023-09-19-19-56.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/12662850/log_2023-09-19-19-56.txt)


请问如何稳定唤出命令行，我使用gui启动时，经常命令行页面出不来

**Comment by CHNZYX** [comment]
我觉得我说的够明白了，需要的是"log.txt"。命令行点击显隐

**Comment by f59375543** [comment]
> 我觉得我说的够明白了，需要的是"log.txt"。命令行点击显隐

抱歉，我理解错误了

我重新校验了一遍后，目前没有撞墙问题了，但是无法暂停还是出现了
[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/12663238/log.txt)



虽然
INFO [2023-09-19 23:25:38,092] [states.py:222] 停止运行
显示已经停止，但是鼠标还在动，点了半天才点到关闭应用

**Comment by CHNZYX** [comment]
看上去没出问题，你说的后台运行问题已经解决了吗

**Comment by f59375543** [comment]
> 看上去没出问题，你说的后台运行问题已经解决了吗

谢谢作者，后台运行的话，我反复测试了五次，好像我每次注销另一个账户，然后重新打开后，都必须重新校验一遍，不然会撞墙，但是校验以后就不会撞墙了，所以程序本身应该没有问题，可能是多账户打开的时候影响了分辨率什么的？我再找一下自己的问题吧，既然校验以后就可以继续使用，就不劳烦作者了，假如我发现新情况再汇报。

最后再次多谢作者。
