### ISSUE TITLE
最新版无限平A[Bug]: 

### ISSUE THREAD

**Issue by MicroDust-real** [CHNZYX/Auto_Simulated_Universe#210]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v5.81 lowest v5.31

### 重现步骤

进图无限平A,换角色/换地图/校准均无用

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

无限AAAA

### 日志记录

INFO [2023-09-25 16:27:58,823] [states.py:40] 当前版本：v5.81 Fixed  当前命途：巡猎
INFO [2023-09-25 16:28:00,842] [states.py:52] 版本下限：v5.31
INFO [2023-09-25 16:28:00,842] [utils.py:36] 通知：初始计数：1  开始运行
INFO [2023-09-25 16:28:00,843] [states.py:109] 加载地图
INFO [2023-09-25 16:28:00,916] [states.py:116] 加载地图完成，共 45 张
INFO [2023-09-25 16:28:01,091] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:28:06,259] [utils.py:332] 匹配到图片 ./imgs/floor/ff3.jpg 相似度 0.989213 阈值 0.970000
INFO [2023-09-25 16:28:06,259] [utils.py:563] 当前层数：3
INFO [2023-09-25 16:28:10,364] [utils.py:332] 匹配到图片 ./imgs/z.jpg 相似度 0.963950 阈值 0.950000
INFO [2023-09-25 16:28:29,341] [utils.py:332] 匹配到图片 ./imgs/auto_2.jpg 相似度 0.995050 阈值 0.970000
INFO [2023-09-25 16:28:39,634] [states.py:198] 匹配不到任何图标
INFO [2023-09-25 16:28:41,247] [utils.py:332] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.971659 阈值 0.940000
INFO [2023-09-25 16:28:41,557] [utils.py:332] 匹配到图片 ./imgs/reset.jpg 相似度 0.999260 阈值 0.940000
INFO [2023-09-25 16:28:44,410] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:07,118] [utils.py:36] 通知：地图-1，当前层数:3  暂离
ERROR [2023-09-25 16:29:07,119] [states.py:502] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-09-25 16:29:07,391] [utils.py:332] 匹配到图片 ./imgs/setting.jpg 相似度 0.984525 阈值 0.980000
INFO [2023-09-25 16:29:16,259] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.999238 阈值 0.970000
INFO [2023-09-25 16:29:17,972] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:18,455] [states.py:198] 匹配不到任何图标
INFO [2023-09-25 16:29:20,285] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.947789 阈值 0.940000
INFO [2023-09-25 16:29:21,982] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:22,457] [states.py:198] 匹配不到任何图标
INFO [2023-09-25 16:29:24,220] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.947500 阈值 0.940000
INFO [2023-09-25 16:29:25,910] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:26,378] [states.py:198] 匹配不到任何图标
INFO [2023-09-25 16:29:28,203] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.947430 阈值 0.940000
INFO [2023-09-25 16:29:29,904] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:30,347] [states.py:198] 匹配不到任何图标
INFO [2023-09-25 16:29:32,129] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.946911 阈值 0.940000
INFO [2023-09-25 16:29:33,843] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:34,299] [states.py:198] 匹配不到任何图标
INFO [2023-09-25 16:29:36,126] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.947476 阈值 0.940000
INFO [2023-09-25 16:29:37,777] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:38,225] [states.py:198] 匹配不到任何图标
INFO [2023-09-25 16:29:40,029] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.948684 阈值 0.940000
INFO [2023-09-25 16:29:41,715] [utils.py:332] 匹配到图片 ./imgs/run.jpg 相似度 0.990720 阈值 0.910000
INFO [2023-09-25 16:29:45,778] [utils.py:332] 匹配到图片 ./imgs/floor/ff3.jpg 相似度 0.989265 阈值 0.970000

### 补充说明（可选）

上周5.8一切正常,更新之后反倒无限A了

**Comment by MicroDust-real** [comment]
日志可能没准确对应上时间点 但总之就是无限A)

**Comment by CHNZYX** [comment]
请附上截图

**Comment by MicroDust-real** [comment]
努力复现中

**Comment by MicroDust-real** [comment]
<img width="960" alt="Snipaste_2023-09-25_17-11-34" src="https://github.com/CHNZYX/Auto_Simulated_Universe/assets/61410757/49c3d7c6-fdbf-46e8-a5da-24229042e412">
<img width="960" alt="Snipaste_2023-09-25_17-10-18" src="https://github.com/CHNZYX/Auto_Simulated_Universe/assets/61410757/e738e94b-4ecf-4733-83c8-861b721872b7">
<img width="960" alt="Snipaste_2023-09-25_17-11-26" src="https://github.com/CHNZYX/Auto_Simulated_Universe/assets/61410757/e4e588e1-7994-44bf-98fe-43ffe7aa16bb">

**Comment by CHNZYX** [comment]
已修复
