### ISSUE TITLE
[Feat]: 希望能够选择(禁止/开启)跑步

### ISSUE THREAD

**Issue by bendyxz** [CHNZYX/Auto_Simulated_Universe#212]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

事情是这样的...都怪我挂机的PC太菜, 运行起来反应慢, 跑步会错过对话框.
在事件, 遭遇, 这样的房间里, 直接就跑过那个对话卡片. 然后到尽头来回转几次, 没能回去识别, 然后开了重置, 重来一次, 又重复前面的...最后放弃了这个宇宙.
目前我手动设置把跑步改为长按, 就可以正常使用, 但好像又影响到另一个锄大地的项目orz
我感觉这点小地方, 赶路反而影响稳定性, 建议可以选择性跑步

**Comment by CHNZYX** [comment]
增加选项会导致代码太过繁杂，所以不会再支持低性能电脑
