### ISSUE TITLE
[Bug]: 5.8.2版本特定场景意外停止

### ISSUE THREAD

**Issue by SpecterHi** [CHNZYX/Auto_Simulated_Universe#213]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.8.2

### 重现步骤

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/2437251/5a01f255-e16e-41e3-b2f0-26e2dc33e193)

模拟宇宙三，如果随机到这个场景的时候（往往是十二层休整），就有几率自动退出自动。截图是自动退出后游戏停住的时刻。

### 期望的结果是什么？

继续自动操作

### 实际的结果是什么？

自动退出了自动。在terminal里面看到提示的确是退出了。

**Comment by CHNZYX** [comment]
会在下版本修复

**Comment by SpecterHi** [comment]
感谢确认和回复！
只是想报告下模拟宇宙七也会在同一个场景（十二层休整）卡住
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/2437251/c47c9da0-575a-4ded-a701-26f9fa48c1b7)
这次截到了console的输出：
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/2437251/d1bfd054-81fa-41e8-a804-5589d8bf68c7)

**Comment by SpecterHi** [comment]
呃……这张类似的图也会……第7宇宙5/13……

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/2437251/1322bec5-b0f8-41b3-bc7c-9612829c6234)
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/2437251/70256072-454f-4f5a-ae21-3b331f6f1fec)

**Comment by CHNZYX** [comment]
会在下个版本修复
