### ISSUE TITLE
[Bug]: 这张图必卡住

### ISSUE THREAD

**Issue by kotoricon** [CHNZYX/Auto_Simulated_Universe#215]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.82

### 重现步骤

目前测试下来就这张图识别有问题必卡住，上周一周二刷的时候也遇到过
![20231004202240](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/8659834/02c35630-bb94-421e-bcc4-e200367bd61c)
![20231004202301](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/8659834/b3a750b8-0382-495a-973e-4109c0989009)
![20231004202422](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/8659834/40c97799-a433-4acb-a888-9ec97432b3ca)

### 期望的结果是什么？

fix

### 实际的结果是什么？

fix

**Comment by CHNZYX** [comment]
你可以重新录图试试，然后发出来。
然后可以告诉我这是哪个世界的图，我碰到问题也会修

**Comment by kotoricon** [comment]
应该就是雅利洛边缘通路的这块地方，视频在这里：
https://drive.google.com/file/d/1jlHeGXVKdNjpw9__86WJcnrJGqzvbnSp/view?usp=drive_link

刚才那次已经自己手动过掉了所以不一定能遇到。总之就是一直撞墙找不到方向

**Comment by CHNZYX** [comment]
我的意思是，第几个宇宙

**Comment by kotoricon** [comment]
4和6应该都有，遇到的频率很低可能刷满30多次就遇到一两次这图

**Comment by kotoricon** [comment]
又遇到它了，无限撞墙 https://drive.google.com/file/d/1qQzosZ0Eupp7kuKSaZIFk4MPCtjdbsRR/view?usp=sharing

**Comment by CHNZYX** [comment]
重复录屏没有意义，你可以重新录图，或者等更新
