### ISSUE TITLE
[Bug]: 5.82版本依然无限平A

### ISSUE THREAD

**Issue by MHBZHY** [CHNZYX/Auto_Simulated_Universe#217]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.82

### 重现步骤

从站立在模拟宇宙门口开始执行自动化脚本，进入宇宙选择界面、选人界面、选择命途界面，均无问题，一直到进入地图，日志开始不停报“匹配不到任何图标”，我在之前的issue中看到类似错误，但日志略有不同，他的日志是会尝试自动退出的，而我的不会，只会不停显示“匹配不到任何图标”，除非被野怪打到进入战斗。战斗结束后选择祝福也是识别没有问题的，随后重新回到地图依然重复上述错误，详情可见日志。

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

进入任意图，均不断平A

### 日志记录

2 0 2 3 - 1 0 - 1 1   2 1 : 3 7 : 4 7 . 5 9 7 2 3 2 0   [ W : o n n x r u n t i m e : D e f a u l t ,   o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 1 8 2 7   o n n x r u n t i m e : : p y t h o n : : C r e a t e I n f e r e n c e P y b i n d S t a t e M o d u l e ]   I n i t   p r o v i d e r   b r i d g e   f a i l e d .
 INFO [2023-10-11 21:37:47,627] [admin.py:29] isUserAdmin - CheckTokenMembership returned: True
INFO [2023-10-11 21:37:59,087] [align_angle.py:29] 开始校准
WARNING [2023-10-11 21:37:59,299] [utils.py:106] 等待游戏窗口
INFO [2023-10-11 21:37:59,299] [utils.py:138] DPI: 2.25 A:0.05
INFO [2023-10-11 21:37:59,299] [utils.py:141] TEXT: 崩坏：星穹铁道
[227]
[130]
[184 155 172]
INFO [2023-10-11 21:38:13,883] [align_angle.py:70] 校准完成
WARNING [2023-10-11 21:38:20,774] [utils.py:106] 等待游戏窗口
INFO [2023-10-11 21:38:20,775] [utils.py:138] DPI: 2.25 A:0.19
INFO [2023-10-11 21:38:20,775] [utils.py:141] TEXT: 崩坏：星穹铁道
INFO [2023-10-11 21:38:21,778] [states.py:40] 当前版本：v5.82 Omega  当前命途：巡猎
INFO [2023-10-11 21:38:22,764] [states.py:52] 版本下限：v5.31
INFO [2023-10-11 21:38:22,764] [states.py:102]  自动领取沉浸奖励
INFO [2023-10-11 21:38:22,861] [utils.py:36] 通知：初始计数：0  开始运行 自动领取沉浸奖励
INFO [2023-10-11 21:38:22,862] [states.py:109] 加载地图
INFO [2023-10-11 21:38:23,272] [states.py:116] 加载地图完成，共 45 张
INFO [2023-10-11 21:38:23,380] [utils.py:332] 匹配到图片 ./imgs/f.jpg 相似度 0.982585 阈值 0.970000
INFO [2023-10-11 21:38:25,305] [utils.py:332] 匹配到图片 ./imgs/init.jpg 相似度 0.975463 阈值 0.970000
INFO [2023-10-11 21:38:27,023] [utils.py:332] 匹配到图片 ./imgs/begin.jpg 相似度 0.979893 阈值 0.970000
INFO [2023-10-11 21:38:29,137] [utils.py:332] 匹配到图片 ./imgs/start.jpg 相似度 0.975298 阈值 0.970000
INFO [2023-10-11 21:38:33,308] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:38:33,554] [utils.py:332] 匹配到图片 ./imgs/fate.jpg 相似度 0.959146 阈值 0.955000
识别结果： |毁灭|巡猎|欢愉|丰饶|虚无|记忆|存护|  识别到： 巡猎
INFO [2023-10-11 21:38:34,846] [utils.py:332] 匹配到图片 ./imgs/fate_2.jpg 相似度 0.975950 阈值 0.970000
INFO [2023-10-11 21:38:44,498] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:38:46,199] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.951466 阈值 0.940000
INFO [2023-10-11 21:38:48,210] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:38:51,928] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:38:55,648] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:38:59,350] [states.py:198] 匹配不到任何图标
WARNING [2023-10-11 21:39:02,574] [states.py:162] 等待游戏窗口
INFO [2023-10-11 21:39:04,557] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:08,269] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:11,977] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:15,683] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:19,388] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:23,098] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:26,827] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:30,524] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:34,212] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:39:48,037] [utils.py:332] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.973272 阈值 0.970000
INFO [2023-10-11 21:39:48,338] [utils.py:332] 匹配到图片 ./imgs/reset.jpg 相似度 0.993266 阈值 0.970000
识别结果： |「丰饶」|「巡猎」|「毁灭」|  识别到： 丰饶
识别结果： |回生|桑弧蓬失|破坏性耀发|  识别到：
识别结果： |「丰饶」|「巡猎」|「毁灭」|  识别到： 巡猎
INFO [2023-10-11 21:39:54,130] [utils.py:332] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.971335 阈值 0.970000
INFO [2023-10-11 21:39:54,431] [utils.py:332] 匹配到图片 ./imgs/reset.jpg 相似度 0.993266 阈值 0.970000
识别结果： |「丰饶」|「丰饶」|「记忆」|  识别到： 记忆
识别结果： |甘露|回生|体验：病痛的折磨|  识别到：
识别结果： |「丰饶」|「丰饶」|「记忆」|  识别到：
识别结果： |。「丰饶，。|「记忆，。|。「巡猎，。|  识别到： 记忆
识别结果： |宝光烛日月|体验：疏离的煎熬|电射牛斗|  识别到：
识别结果： |「丰饶」|「记忆」|「巡猎」|  识别到： 巡猎
INFO [2023-10-11 21:40:02,952] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:40:04,648] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.947256 阈值 0.940000
INFO [2023-10-11 21:40:06,640] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:40:10,334] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:40:14,013] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:40:17,710] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:40:21,376] [states.py:198] 匹配不到任何图标
INFO [2023-10-11 21:40:25,063] [states.py:198] 匹配不到任何图标
WARNING [2023-10-11 21:40:26,568] [states.py:162] 等待游戏窗口
INFO [2023-10-11 21:40:28,266] [states.py:855] 尝试停止运行
INFO [2023-10-11 21:40:28,572] [states.py:223] 停止运行
INFO [2023-10-11 21:40:28,574] [states.py:855] 尝试停止运行
INFO [2023-10-11 21:40:28,576] [utils.py:36] 通知：   已退出自动化

**Comment by CHNZYX** [comment]
请给出截图

**Comment by MHBZHY** [comment]
https://github.com/CHNZYX/Auto_Simulated_Universe/assets/19261872/98d90a58-8ba4-4596-b93b-aa5e7d3f7241

录了个视频，方便判断问题

**Comment by CHNZYX** [comment]
打开调试模式，然后贴一下命令行输出

**Comment by MHBZHY** [comment]
2 0 2 3 - 1 0 - 1 2   2 3 : 1 5 : 5 7 . 2 0 8 9 0 2 9   [ W : o n n x r u n t i m e : D e f a u l t ,   o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 1 8 2 7   o n n x r u n t i m e : : p y t h o n : : C r e a t e I n f e r e n c e P y b i n d S t a t e M o d u l e ]   I n i t   p r o v i d e r   b r i d g e   f a i l e d .
 INFO [2023-10-12 23:15:57,241] [admin.py:29] isUserAdmin - CheckTokenMembership returned: True
INFO [2023-10-12 23:17:04,714] [align_angle.py:29] 开始校准
WARNING [2023-10-12 23:17:04,961] [utils.py:106] 等待游戏窗口
INFO [2023-10-12 23:17:04,962] [utils.py:138] DPI: 2.25 A:0.28
INFO [2023-10-12 23:17:04,962] [utils.py:141] TEXT: 崩坏：星穹铁道
[96]
[330]
[292  26 137]
INFO [2023-10-12 23:17:19,814] [align_angle.py:70] 校准完成
WARNING [2023-10-12 23:17:28,936] [utils.py:106] 等待游戏窗口
INFO [2023-10-12 23:17:28,936] [utils.py:138] DPI: 2.25 A:0.23
INFO [2023-10-12 23:17:28,936] [utils.py:141] TEXT: 崩坏：星穹铁道
INFO [2023-10-12 23:17:29,938] [states.py:40] 当前版本：v5.82 Omega  当前命途：巡猎
INFO [2023-10-12 23:17:36,516] [states.py:52] 版本下限：v5.31
INFO [2023-10-12 23:17:36,516] [states.py:102]  自动领取沉浸奖励
INFO [2023-10-12 23:17:36,622] [utils.py:36] 通知：初始计数：0  开始运行 自动领取沉浸奖励
INFO [2023-10-12 23:17:36,623] [states.py:109] 加载地图
INFO [2023-10-12 23:17:37,201] [states.py:116] 加载地图完成，共 45 张
INFO [2023-10-12 23:17:37,334] [utils.py:332] 匹配到图片 ./imgs/f.jpg 相似度 0.982585 阈值 0.970000
DEBUG [2023-10-12 23:17:37,781] [utils.py:172] 按下按钮 f，等待 0 秒后释放
0.0 29325
0.0 0
INFO [2023-10-12 23:17:39,353] [utils.py:332] 匹配到图片 ./imgs/init.jpg 相似度 0.977822 阈值 0.970000
0.0 0
0.0 0
INFO [2023-10-12 23:17:41,090] [utils.py:332] 匹配到图片 ./imgs/begin.jpg 相似度 0.979938 阈值 0.970000
0.0 0
0.5072686076164246 510
INFO [2023-10-12 23:17:43,211] [utils.py:332] 匹配到图片 ./imgs/start.jpg 相似度 0.975640 阈值 0.970000
0.0 0
0.0 0
INFO [2023-10-12 23:17:44,955] [utils.py:332] 匹配到图片 ./imgs/fate.jpg 相似度 0.973552 阈值 0.970000
识别结果： |毁灭|巡猎|欢愉|丰饶|虚无|记忆|存护|  识别到： 巡猎
0.0 0
INFO [2023-10-12 23:17:46,245] [utils.py:332] 匹配到图片 ./imgs/fate_2.jpg 相似度 0.975840 阈值 0.970000
0.0 0
0.2586617171764374 0
0.26967111229896545 0
0.0 0
0.0 0
0.0 0
0.896967351436615 10710
0.896967351436615 10710
0.896967351436615 10710
0.896967351436615 10710
INFO [2023-10-12 23:17:55,969] [states.py:198] 匹配不到任何图标
0.896967351436615 10710
0.896967351436615 10710
INFO [2023-10-12 23:17:57,705] [utils.py:332] 匹配到图片 ./imgs/yes1.jpg 相似度 0.948137 阈值 0.940000
0.896967351436615 11220
INFO [2023-10-12 23:17:59,685] [states.py:198] 匹配不到任何图标
0.896967351436615 11220
0.896967351436615 11220
0.896967351436615 10710
INFO [2023-10-12 23:18:03,403] [states.py:198] 匹配不到任何图标
0.896967351436615 10710
0.896967351436615 10965
0.896967351436615 10965
INFO [2023-10-12 23:18:07,107] [states.py:198] 匹配不到任何图标
0.896967351436615 10965
0.896967351436615 10965
0.8974481225013733 10965
INFO [2023-10-12 23:18:10,836] [states.py:198] 匹配不到任何图标
0.8974481225013733 10965
0.8974481225013733 11220
0.8974481225013733 11475
INFO [2023-10-12 23:18:14,579] [states.py:198] 匹配不到任何图标
0.8974481225013733 11475
0.8974481225013733 11475
WARNING [2023-10-12 23:18:17,781] [states.py:162] 等待游戏窗口
INFO [2023-10-12 23:18:18,286] [states.py:855] 尝试停止运行
INFO [2023-10-12 23:18:18,783] [states.py:223] 停止运行
INFO [2023-10-12 23:18:18,786] [states.py:855] 尝试停止运行
INFO [2023-10-12 23:18:18,787] [utils.py:36] 通知：   已退出自动化

**Comment by CHNZYX** [comment]
你这就挺奇怪了，运行程序时是否保证关闭了hdr，并使用正常的颜色配置文件？

**Comment by CHNZYX** [comment]
如果还有问题可以贴个游戏截图

**Comment by MHBZHY** [comment]
不好意思，是hdr的问题，我关闭issue了
