### ISSUE TITLE
[Bug]: 遇到事件时很大概率会直接跑过

### ISSUE THREAD

**Issue by Heipen** [CHNZYX/Auto_Simulated_Universe#227]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v5.82

### 重现步骤

用的surface平板在跑性能很差，导致即使画质全开最低也很容易导致遇到事件是直接跑过跑到卡片后面撞墙，此时会自动回头走两步来寻找，但是总是差一点，明明再多走两步就可以碰到。

### 期望的结果是什么？

对于性能过差的设备，希望可以选择遇到事件或过图全程时不要疾跑，慢慢走过去应该能很大程度减少性能过差的影响，或者直接对于这种事件关跑过后的尝试中多往回走几步

### 实际的结果是什么？

如上

**Comment by CHNZYX** [comment]
脚本不会支持性能过低的运行环境。
