### ISSUE TITLE
[Feat]: 能否加一个祝福选择优先级的选项

### ISSUE THREAD

**Issue by kotoricon** [CHNZYX/Auto_Simulated_Universe#230]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

有时候会出现几个好的里面选个最垃圾的一星，好像出现也不是一次两次了
隔壁舰b脚本做的那个穹的模拟器用版本已经有类似的功能了，都是python要不你直接抄一下（

**Comment by CHNZYX** [comment]
有啊，如果对默认优先级不满意，在info.yml里你可以自定义。
