### ISSUE TITLE
[Bug]: 奇物黑名单不生效

### ISSUE THREAD

**Issue by MicroDust-real** [CHNZYX/Auto_Simulated_Universe#231]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.9

### 重现步骤

正常挂机模拟宇宙

### 期望的结果是什么？

不选取愚者面具和齿轮等负面奇物

### 实际的结果是什么？

照选不误.
实际上5.8版本体感不怎么选取负面奇物或者概率很低,33次挂8h左右挺稳的
更新5.9之后8h只通关了20+次,是不是把黑名单变成优先级名单了...
偶尔盯着看感觉他会可着愚者面具拿,太智熄了,8层打完拿个愚者面具全部木大,抱着一堆垃圾祝福和boss大战三百回合然后团灭

**Comment by CHNZYX** [comment]
已修复
