### ISSUE TITLE
[Feat]: 沉浸奖励添加支持使用体力兑换，以及使用其他资源兑换体力

### ISSUE THREAD

**Issue by SlowpokeFisher** [CHNZYX/Auto_Simulated_Universe#233]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

目前沉浸器最多存8个，如果需要自动刷位面遗器需要每两轮回来手动换体力和沉浸器，不是很方便。同时每周刷33次的时间自回体应该也能再换一两次。

可否考虑支持消耗体力，以及添加后备开拓力/燃料/星琼换取体力来兑换沉浸奖励？

另外沉浸奖励页面的相关逻辑全都藏在`get_direc_only_minimap`里了，可否考虑把打开兑换交互界面之后的逻辑拆出来放进`SimulatedUniverse` 或者`UniverseUtils`里，我这边也可以交PR。

**Comment by CHNZYX** [comment]
不会添加体力相关的功能，这是有意为之
