### ISSUE TITLE
[Bug]: 版本更新后，不再有脱离卡死按键

### ISSUE THREAD

**Issue by ZephyrAssa** [CHNZYX/Auto_Simulated_Universe#235]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v5.9

### 重现步骤

以往在一个关卡当中迷路的时候，会自动地使用脱离卡死重置位置，如今这个方法似乎不可行了

### 期望的结果是什么？

使用脱离卡死重置位置

### 实际的结果是什么？

没有脱离卡死了

### 补充说明（可选）

退出再重进同样可以重置位置，希望能改成这样运作

**Comment by CHNZYX** [comment]
已修复
