### ISSUE TITLE
[Bug]: Readme中的文档链接打不开

### ISSUE THREAD

**Issue by shenbourne** [CHNZYX/Auto_Simulated_Universe#240]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

6.051

### 重现步骤

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/121733766/86d17527-2580-4993-9718-56b972ea0038)
Readme中这仨链接打不开
我挂了梯子之后，页面是这样的：
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/121733766/dd18a676-73e4-436e-b70a-4a3ebe2e4546)
把梯子关了之后，页面是这样的：
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/121733766/0b3d20b4-72de-480b-8650-8dca2f0da50b)

### 期望的结果是什么？

能把这些文档移到Github上吗？我的确需要

### 实际的结果是什么？

能把这些文档移到Github上吗？我的确需要

**Comment by CHNZYX** [comment]
已增加备用链接
