### ISSUE TITLE
[Bug]: 模拟宇宙无法正常进入

### ISSUE THREAD

**Issue by ZephyrAssa** [CHNZYX/Auto_Simulated_Universe#245]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v6.051

### 重现步骤

正常开启模拟宇宙就有了

### 期望的结果是什么？

正常运行模拟宇宙

### 实际的结果是什么？

无法识别进入游戏，不能自动进入模拟宇宙

### 补充说明（可选）

新版本模拟宇宙的布局更改了

**Comment by akllcom** [comment]
+1我也是这个问题，新版本布局变动没办法正常使用，具体位置应该是点了第几宇宙之后，那个进入探索或者继续探索那里，无法正常进入

**Comment by Dennis9413** [comment]
+1
游戏更新到1.6版本后.
在模拟世界中初始选择世界的介面中,不能自动进入预选的世界.

**Comment by CHNZYX** [comment]
已适配
