### ISSUE TITLE
[Bug]: 校准失败，命令行报错

### ISSUE THREAD

**Issue by Kotagan** [CHNZYX/Auto_Simulated_Universe#255]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v6.11

### 重现步骤

在双屏电脑的副屏幕上，1920*1080全屏幕，点击校准

### 期望的结果是什么？

校准成功

### 实际的结果是什么？

校准失败

### 日志记录

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/25102488/682d755c-1891-4b4d-8756-a83b39a97b38)

**Comment by CHNZYX** [comment]
参考Q&A，目前没有人复现你的错误
