### ISSUE TITLE
[Bug]: 领完沉浸奖励后报错停止运行

### ISSUE THREAD

**Issue by bin1129** [CHNZYX/Auto_Simulated_Universe#262]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v6.12 lowest v6.1

### 重现步骤

勾选沉浸奖励，进入第六世界，第一个boss打通后，领取沉浸奖励

### 期望的结果是什么？

领完后继续通关

### 实际的结果是什么？

领完后报错停止运行

### 日志记录

INFO [2024-02-23 22:39:02,802] [utils.py:400] 匹配到图片 ./imgs/strange.jpg 相似度 0.966033 阈值 0.955000
识别结果： |记忆火漆|愚者面具x|繁育火漆|  识别到： 繁育火漆?
识别到文本： 点击空白 匹配文本： 点击空白处关闭
INFO [2024-02-23 22:39:06,834] [states.py:199] 匹配不到任何图标
识别到文本： 点击空白 匹配文本： 点击空白处关闭
INFO [2024-02-23 22:39:09,878] [utils.py:400] 匹配到图片 ./imgs/run.jpg 相似度 0.988839 阈值 0.910000
INFO [2024-02-23 22:39:09,944] [utils.py:400] 匹配到图片 ./imgs/ruan.jpg 相似度 0.960581 阈值 0.950000
INFO [2024-02-23 22:39:14,998] [utils.py:400] 匹配到图片 ./imgs/f.jpg 相似度 0.995240 阈值 0.960000
INFO [2024-02-23 22:39:16,725] [utils.py:400] 匹配到图片 ./imgs/bonus_c.jpg 相似度 0.999131 阈值 0.940000
[ WARN:0@291.824] global loadsave.cpp:244 cv::findDecoder imread_('./imgs/lack.jpg'): can't open/read file: check file path/integrity
E: 运行函数时出现错误
Traceback (most recent call last):
  File "gui\choose.py", line 31, in run
  File "states.py", line 973, in start
  File "states.py", line 182, in route
  File "states.py", line 548, in normal
  File "utils\utils.py", line 1284, in get_direc_only_minimap
  File "utils\utils.py", line 372, in check
AttributeError: 'NoneType' object has no attribute 'shape'
INFO [2024-02-23 22:39:18,736] [states.py:904] 尝试停止运行
INFO [2024-02-23 22:39:18,739] [utils.py:33] 通知：   已退出自动化

**Comment by vvincee7** [comment]
我也在第六世界遇到了同样的问题

**Comment by RandyOrlando** [comment]
同样频繁遇到此问题，目前根据报错信息，发现一个临时的解决方案：把imgs文件夹里面的icon.jpg复制一份，改名为lack.jpg。运行了几次，没报错。不确定是否会有其他不良影响。

**Comment by hanuxxx** [comment]
我打的世界8也是同样的问题
手动下载lack.jpg放进文件夹里解决了

**Comment by zhyx1996** [comment]
这里有lack.jpg，是不是自己下下来补上就行了
https://github.com/CHNZYX/Auto_Simulated_Universe/blob/main/imgs/lack.jpg

**Comment by Helly0000** [comment]
> 这里有lack.jpg，是不是自己下下来补上就行了 https://github.com/CHNZYX/Auto_Simulated_Universe/blob/main/imgs/lack.jpg

亲测好使。

**Comment by CHNZYX** [comment]
会在下版本修复
