### ISSUE TITLE
[Feat]: 自定义刷的次数

### ISSUE THREAD

**Issue by fjf010223** [CHNZYX/Auto_Simulated_Universe#265]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

现在是默认刷满34次才停止，不知道能否设置成可以自定义刷到停止的次数，因为有时候自己也会手动打几把玩玩，然后再挂机拿满奖励就不需要刷34次了

**Comment by CHNZYX** [comment]
下版本会在gui版本也增加自定义次数。代码版可以用nums={x}的方式自定义
