### ISSUE TITLE
[Bug]: 在过某张图时出现了匹配图片但无操作的情况

### ISSUE THREAD

**Issue by ghost** [CHNZYX/Auto_Simulated_Universe#266]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

6.12

### 重现步骤

世界八难度4的图

### 期望的结果是什么？

匹配图片并进行相关操作

### 实际的结果是什么？

![图片](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/92812360/79267cc9-3b09-47ba-ab39-d5744d2596e4)
如图，在此图出现了无操作的情况，图中的位置为手动走过后的位置

**Comment by CHNZYX** [comment]
新版本进行了相关优化，如有问题请再次提出issue
