### ISSUE TITLE
[Bug]: 匹配不到任何图标

### ISSUE THREAD

**Issue by mxyooR** [CHNZYX/Auto_Simulated_Universe#267]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

6.12

### 重现步骤

release版本在windows arm64的电脑上运行时，一直匹配不到任何图标，已经调节画质到要求画质，并且多次校准
![FCF0B2E2A10CA3CDF40927546D2EB68F](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/88259089/4aca073f-4543-4913-b71f-91909608a4c3)

### 期望的结果是什么？

识别图标并执行

### 实际的结果是什么？

进入模拟宇宙第七世界后一直平a不动

**Comment by LinkMole** [comment]
遇到了同样的问题，同样的版本，在“按下”f后一直提示“匹配不到任何图标”，卡在世界选择界面，甚至手动操作选择世界、选择命途后仍提示“匹配不到任何图标”

**Comment by LinkMole** [comment]
有可能是分辨率没调对，是1920x1080，不是1920x1200
