### ISSUE TITLE
[Bug]: 领取沉浸奖励后无法自动点击空白处关闭页面

### ISSUE THREAD

**Issue by wzkagms** [CHNZYX/Auto_Simulated_Universe#269]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

6.12

### 重现步骤

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/104975751/6693eda5-a597-4a87-ab00-4afb4d4635cf)
领取沉浸奖励后无法点击空白处继续运行，椰羊自动助手提示退出自动化，三次沉浸奖励均如此

### 期望的结果是什么？

点击空白处，继续运行

### 实际的结果是什么？

无法继续运行
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/104975751/9282d1b2-0dd4-41d2-9528-463b38a8ef5e)

### 日志记录

[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/14471805/log.txt)

**Comment by CHNZYX** [comment]
会在下版本修复
