### ISSUE TITLE
使用速通模式后黄泉没有使用秘技砍人，只往关底冲

### ISSUE THREAD

**Issue by f59375543** [CHNZYX/Auto_Simulated_Universe#278]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v6.3 

### 重现步骤

和以前一样，没有任何改动

### 期望的结果是什么？

黄泉自动用秘技砍人

### 实际的结果是什么？

黄泉没有用秘技砍人

**Comment by f59375543** [comment]
黄泉已放在一号位，只会在boss房才使用秘技，在小怪房只平A开怪
补充log
[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/14820388/log.txt)




更新后续，奇怪了，重启电脑后，有些关卡开始秘技砍人，有些还是只是平A开怪，没搞懂触发原因
补充新log
[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/14820956/log.txt)

**Comment by f59375543** [comment]
更新后续，奇怪了，重启电脑后，有些关卡开始秘技砍人，有些还是只是平A开怪，没搞懂触发原因

附带新的log

**Comment by htshts1115** [comment]
速通模式定义就是只打关底怪

**Comment by f59375543** [comment]
> 速通模式定义就是只打关底怪

我指的是没有秘技开怪，而是普攻开怪，不过这是随机触发，无法稳定复现
