### ISSUE TITLE
update.bat is not working properly

### ISSUE THREAD

**Issue by ne587458** [CHNZYX/Auto_Simulated_Universe#28]
update.bat is not working properly

'git' is not recognized as an internal or external command, executable program or batch file.

**Comment by CHNZYX** [comment]
You need to install git first

**Comment by ne587458** [comment]
i have installed
[https://imgur.com/T4vi8XV.png](url)

**Comment by CHNZYX** [comment]
Download the repository again  to ensure it is the latest
