### ISSUE TITLE
[Bug]: 现在的问题也太多了

### ISSUE THREAD

**Issue by kotoricon** [CHNZYX/Auto_Simulated_Universe#292]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

6.3

### 重现步骤

1. 2.1（？）开始的各种新寻路问题，仙舟几张新加入模拟的地图（如麟渊境的几个拐角较多的图）的寻路应该也是完全还没做，一张图从早上6点卡到刚才9点半还没过去反复重进，如果再次遇到能卡一天。
2. [一些以前提过的老bug半年了现在还没修复，或者该说修复了一半寻路依然有问题要反复试很久才能过去。（如[https://github.com/CHNZYX/Auto_Simulated_Universe/issues/215#issue-1926106098](url)）建议把一些拐角较多的图都多测试几遍再说
3. 通关次数那个统计即便设置上限依然会无限运行，而且有时候发现即便没通关boss（如10/13, 11/13 6/13等）单纯打过精英也算一次通关次数
4. 老版本打精英怪之前会开全角色秘技好像现在也不会放了只会放第一个人的然后直接开始战斗
5. 程序本身能重复运行，缺少一个已在运行检测机制。会造成本身运行混乱不停试各种操作

### 期望的结果是什么？

该更新了咕咕咕

### 实际的结果是什么？

无

**Comment by dsyyy7** [comment]
第三条我遇到过很多次了

速通模式，角色很容易在找方向的途中停下来，然后被怪偷袭，浪费好多时间

**Comment by sykuu5414** [comment]
3.这条遇到同样问题，设置上限没有用不会自动停止

**Comment by sadmiroir** [comment]
确实，现在毛病多到还不如手动
昨天早上出门上班开始挂了一天居然20次都没跑完。要以往几个月前的版本最多7-8个小时就完事了，那会甚至还没黄泉软妹这种能一路冲刺的角色

**Comment by CHNZYX** [comment]
最近没有时间更新。
现在自动化的主要作用是刷狗粮，建议找一个最稳定的世界挂机

**Comment by sadmiroir** [comment]
其实你现在把麟渊境解决一下能解决大部分耗时问题感觉跟模拟几没什么关系
就拿题主所说的麟渊境举例，大概率那几个图会出现在刚进去的1-3图或者第一次休整后的6-8图。因为现在的那几个图没有做寻路导致反复原地打转只能强制结束。基本上一旦卡在那几个图里就是半小时到一小时一次图都没刷（我刚看着挂过一次就是这样，在第一个图就遇到转了十多分钟只能退出重开）

**Comment by kotoricon** [comment]
跟上面说的差不多，麟渊境问题过于严重，别的其实都算小问题
