### ISSUE TITLE
[Bug]: 6.19版本更新后 选择奇物页面会卡住

### ISSUE THREAD

**Issue by htshts1115** [CHNZYX/Auto_Simulated_Universe#294]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

6.3

### 重现步骤

可能是没有正确进入选择奇物逻辑，进入了选择祝福逻辑

### 期望的结果是什么？

点确认

### 实际的结果是什么？

没点确认，卡住

### 日志记录

INFO [2024-06-19 20:33:02,232] [utils.py:1376] need_confirm 区域二精类
INFO [2024-06-19 20:33:02,544] [utils.py:782] 交互点生效：1
INFO [2024-06-19 20:33:02,544] [utils.py:791] 地图-1已完成,相似度-1,进入4层
INFO [2024-06-19 20:33:04,040] [utils.py:405] 匹配到图片 ./imgs/run.jpg 相似度 0.990167 阈值 0.910000
INFO [2024-06-19 20:33:06,149] [utils.py:405] 匹配到图片 ./imgs/z.jpg 相似度 0.964666 阈值 0.950000
INFO [2024-06-19 20:33:22,825] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:33:22,960] [utils.py:405] 匹配到图片 ./imgs/c.jpg 相似度 0.985806 阈值 0.985000
INFO [2024-06-19 20:33:32,778] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:33:38,644] [utils.py:405] 匹配到图片 ./imgs/auto_2.jpg 相似度 0.996545 阈值 0.955000
INFO [2024-06-19 20:34:06,832] [utils.py:405] 匹配到图片 ./imgs/c.jpg 相似度 0.985806 阈值 0.985000
INFO [2024-06-19 20:34:07,178] [utils.py:405] 匹配到图片 ./imgs/auto_2.jpg 相似度 0.975811 阈值 0.970000
INFO [2024-06-19 20:34:08,712] [utils.py:405] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.970811 阈值 0.970000
INFO [2024-06-19 20:34:09,014] [utils.py:405] 匹配到图片 ./imgs/reset.jpg 相似度 0.997994 阈值 0.970000
INFO [2024-06-19 20:34:10,187] [utils.py:405] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.971502 阈值 0.970000
INFO [2024-06-19 20:34:18,067] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:34:20,291] [utils.py:405] 匹配到图片 ./imgs/yes1.jpg 相似度 0.946638 阈值 0.940000
INFO [2024-06-19 20:34:44,157] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:35:10,167] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:35:37,192] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:36:15,376] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:36:41,526] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:37:07,760] [states.py:200] 匹配不到任何图标
INFO [2024-06-19 20:37:43,395] [states.py:200] 匹配不到任何图标

**Comment by ctf01am** [comment]
确实，这个问题我也碰见了

**Comment by Klamist** [comment]
是无法识别奇物选择界面了，不是没点确认。
说一下修复方法：
自己在奇物选择界面，截一下左上角的图，然后去img里编辑strange.jpg，重新覆盖一下。比如我这个就ok
![strange](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/33776012/23e9f63a-8e7e-454e-bbbc-1baca79d5d0e)

**Comment by Xiaolinzzz1** [comment]
> 是无法识别奇物选择界面了，不是没点确认。 说一下修复方法： 自己在奇物选择界面，截一下左上角的图，然后去img里编辑strange.jpg，重新覆盖一下。比如我这个就ok ![strange](https://private-user-images.githubusercontent.com/33776012/341276432-23e9f63a-8e7e-454e-bbbc-1baca79d5d0e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzUwNzYsIm5iZiI6MTcxODkzNDc3NiwicGF0aCI6Ii8zMzc3NjAxMi8zNDEyNzY0MzItMjNlOWY2M2EtOGU3ZS00NTRlLWJiYmMtMWJhY2E3OWQ1ZDBlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAxNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZDg2MDk1YTI0NmNjYmNlYjU2ZjBlMmIyZjIyNjhmZDA2MDUwMjBhNmRkOWQ4ZjViYmZkNDAxMDlmNDA5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cn771rxePbtmoLc1ZmincqGZKWUwjrzKa5ALUqVvS1k)

刚试了一下这个方法，不行， 还是卡在选择奇物的界面，自己截图包括用您提供的图

**Comment by Xiaolinzzz1** [comment]
不仅会卡在选择奇物上， 还遇到了 卡在事件“怜人系法” 上 还有刚启动模拟宇宙 选祝福上
![Uploading image.png…]()

**Comment by Klamist** [comment]
我在另一个issue里提过了，有很多截图要换……以及ocr识别的位置也需要改。

如果你电脑已经装了python的话也许可以试试这个（没编译，所以得自己有python的时候运行才行。只改了一点源码和图）。我是已经挂完30次了。
https://github.com/Klamist/Siuuu/tree/old

**Comment by Xiaolinzzz1** [comment]
> 我在另一个issue里提过了，有很多截图要换……以及ocr识别的位置也需要改。
> 
> 如果你电脑已经装了python的话也许可以试试这个（没编译，所以得自己有python的时候运行才行。只改了一点源码和图）。我是已经挂完30次了。 https://github.com/Klamist/Siuuu/tree/old

感谢大佬、！！

**Comment by Xiaolinzzz1** [comment]
问题已解决。 下载源码版 按照大佬的办法 替换图片， 编辑PY文件， 就可以运行了， 设置好了info.yml里面的fate：命途

> 我在另一个issue里提过了，有很多截图要换……以及ocr识别的位置也需要改。
> 
> 如果你电脑已经装了python的话也许可以试试这个（没编译，所以得自己有python的时候运行才行。只改了一点源码和图）。我是已经挂完30次了。 https://github.com/Klamist/Siuuu/tree/old
