### ISSUE TITLE
[Feat]: 关于差分宇宙的祝福选择问题

### ISSUE THREAD

**Issue by MarkeTT0wn** [CHNZYX/Auto_Simulated_Universe#298]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

新的版本上线后支持了差分宇宙，我就自己跑了一下，关于祝福的选择上我发现可以优化。
在祝福选择的时候右上角还是左上角会出现图标来提示你建议选择这个祝福，比如黄色的书本代表着你从未选择这个祝福，可以获得手机奖励；绿色的图标表示你选择的祝福对你没有展开的方程式有用，建议选择。因此可不可以判断假若出现了那两个图标就选择相对应的祝福呢？

**Comment by CHNZYX** [comment]
祝福选择目前只以收益最大化为目标，不会考虑凑方程和开图鉴。
凑方程：收益不高，比如流萤队拿了个欢愉方程，就算凑出来也没什么用。这种情况不少见。
开图鉴：自动化打多了什么图鉴开不出？（除了超验3）

**Comment by MarkeTT0wn** [comment]
> 祝福选择目前只以收益最大化为目标，不会考虑凑方程和开图鉴。 凑方程：收益不高，比如流萤队拿了个欢愉方程，就算凑出来也没什么用。这种情况不少见。 开图鉴：自动化打多了什么图鉴开不出？（除了超验3）

现在用了大佬的脚本两周多了，发现差分宇宙核心玩法就是凑方程，你凑出方程的伤害还是会比优先选择祝福高很多，效率也会高一大截。在差分宇宙里米哈游把怪物的血量调得很高，如果没有方程的数值叠加的话效率会很低。现在脚本挂机九小时只通关了14次，希望大佬能慢慢优化，谢谢大佬
