### ISSUE TITLE
地图几个都合不上

### ISSUE THREAD

**Issue by RogerAbyss** [CHNZYX/Auto_Simulated_Universe#3]
大佬录的模拟6 难度1吗？ 会不会难度等级不一样 地图不一样？ 我这边难度2 连续试了三个地图 都对不上号

**Comment by CHNZYX** [comment]
是否进行了校准？难度和地图无关。

**Comment by CHNZYX** [comment]
地图已经接近录入完毕，若有测图意愿可以加群
