### ISSUE TITLE
[Bug]: 选择难度和保存存档卡住

### ISSUE THREAD

**Issue by CN-YoungYang** [CHNZYX/Auto_Simulated_Universe#300]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

v7.11 GUI版本

### 重现步骤

1，自定义存档的时候会频繁 触发存档管理
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/25340441/682168a8-ef8b-4ca4-aa2c-27777ccb73e5)
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/25340441/1eb3049b-580c-44a9-953d-d0fa6012c188)

2，选择难度时候会卡住,
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/25340441/7ee09d92-7999-47da-bfb4-ddabb82b84a8)
![ODDTI@2PPL 8$7E6FU4CG$I](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/25340441/4f071225-2bf1-4b7c-b913-3ee7c9b3b125)

### 期望的结果是什么？

1，存档后,返回继续
2，启动差分宇宙

### 实际的结果是什么？

1，卡存档界面
2，卡启动界面

### 补充说明（可选）

在卡启动界面的时候。
1，调整难度，软件会自动点击难度 - , 让难度变为0
2，点击 左侧 难度5 难度4，大概率会 触发程序继续运行,  程序自己 点 启动差分宇宙

**Comment by CHNZYX** [comment]
没有类似issue，判断为已经在后续版本修复。如果还有问题可以新开issue。
