### ISSUE TITLE
[Bug]: 新版本的计数方式仍未生效

### ISSUE THREAD

**Issue by i-cecreamer** [CHNZYX/Auto_Simulated_Universe#307]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

7.13

### 重现步骤

只要不是一次性运行34次，还是会和之前一样，从0开始计数34次

### 期望的结果是什么？

一星期内分次运行，最高截止为设定值，而不是每次使用都以34次为前提

### 实际的结果是什么？

运行次数超出了每周最大值

### 日志记录

INFO [2024-07-05 02:55:20,507] [diver.py:166] 触发 差分宇宙中:位面
INFO [2024-07-05 02:55:20,779] [log.py:54] area_text: 1313第三位面区域首领 deep: 0
INFO [2024-07-05 02:55:21,533] [log.py:54] area_text: 1313第三位面区域首领 deep: 0
INFO [2024-07-05 02:55:23,131] [log.py:54] floor: 13 state: 1 area: 首领 text: 1313第三位面区域首领
INFO [2024-07-05 02:55:27,742] [utils.py:35] 通知：计数:34 剩余:29 已使用：1小时35分钟  平均19分钟一次  预计剩余9小时16分钟  已完成
INFO [2024-07-05 02:55:29,406] [diver.py:166] 触发 确认界面:确认
INFO [2024-07-05 02:55:29,406] [diver.py:133] 点击 确认:[1152, 1205, 648, 678]
INFO [2024-07-05 02:55:34,675] [diver.py:166] 触发 探索结束:返回主界面
INFO [2024-07-05 02:55:34,676] [log.py:54] saved_num: 0 save_cnt: 0
INFO [2024-07-05 02:55:44,863] [diver.py:166] 触发 加载界面:开始游戏
INFO [2024-07-05 02:55:44,863] [diver.py:133] 点击 开始游戏:[1512, 1624, 938, 971]
INFO [2024-07-05 02:55:48,048] [diver.py:166] 触发 模式选择:模式选择
INFO [2024-07-05 02:55:48,048] [diver.py:133] 点击 常规演算:[531, 673, 297, 333]
INFO [2024-07-05 02:55:52,427] [diver.py:166] 触发 启动[差分宇宙]:启动
INFO [2024-07-05 02:55:53,330] [diver.py:133] 点击 启动:[1575, 1760, 945, 976]
INFO [2024-07-05 02:55:55,737] [diver.py:166] 触发 启动[差分宇宙]:启动
INFO [2024-07-05 02:55:56,640] [diver.py:133] 点击 启动:[1575, 1760, 945, 976]
INFO [2024-07-05 02:56:03,985] [diver.py:166] 触发 方程选择:方程
INFO [2024-07-05 02:56:03,985] [log.py:54] [{'raw_text': '惑世蠢役0503孢子上限提高角色的终结技攻击使孢子爆裂后对攻击目标造成1次终结技伤害爆裂的孢子越多该伤害越高繁育智识', 'box': [1202, 1642, 450, 850], 'score': -1}, {'raw_text': '激雷乐队0503敌方目标陷入冻结状态时立即触发1次持续伤害每有1个持续伤害状态陷入1层怀疑虚无记忆', 'box': [261, 701, 450, 850], 'score': -4}, {'raw_text': '赏金猎人0404角色造成暴击伤害后有概率额外造成原伤害一定比例的暴击伤害该伤害视为追加攻击伤害巡猎欢愉', 'box': [731, 1171, 450, 850], 'score': -6}]
INFO [2024-07-05 02:56:07,940] [diver.py:166] 触发 祝福选择:祝福
INFO [2024-07-05 02:56:07,940] [log.py:54] [{'raw_text': '存护之路获得5个随机祝福其中包含13个存护祝福开拓', 'box': [254, 694, 450, 850], 'score': -2}, {'raw_text': '巡猎之路获得5个随机祝福其中包含13个巡猎祝福开拓', 'box': [732, 1172, 450, 850], 'score': -2}, {'raw_text': '繁育之路获得5个随机祝福其中包含13个繁育祝福开拓', 'box': [1209, 1649, 450, 850], 'score': -2}]
INFO [2024-07-05 02:56:14,057] [diver.py:166] 触发 点击空白处关闭:空白
INFO [2024-07-05 02:56:14,058] [diver.py:133] 点击 点击空白:[864, 1039, 995, 1026]
INFO [2024-07-05 02:56:18,041] [diver.py:166] 触发 点击空白处关闭:空白
INFO [2024-07-05 02:56:18,041] [diver.py:133] 点击 点击空白:[865, 1036, 979, 1006]
INFO [2024-07-05 02:56:21,120] [diver.py:166] 触发 差分宇宙中:位面
INFO [2024-07-05 02:56:21,426] [log.py:54] area_text: 113第一位面区域战斗 deep: 0
INFO [2024-07-05 02:56:22,233] [log.py:54] area_text: 113第一位面区域战斗 deep: 0
INFO [2024-07-05 02:56:24,001] [log.py:54] floor: 1 state: 0 area: 战斗 text: 113第一位面区域战斗

### 补充说明（可选）

![Uploading QQ截图20240705031914.png…]()

**Comment by CHNZYX** [comment]
计数的逻辑为：本次运行的次数。如果本周已经运行了10次，可以把次数改为24次。
可以理解你的想法，但是涉及其它项目的调用，不会修改重要参数的逻辑。
