### ISSUE TITLE
[Feat]: 请问是否能支持用配置更改想要刷取的协议阈值呢？

### ISSUE THREAD

**Issue by linbeyoung** [CHNZYX/Auto_Simulated_Universe#309]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 以及 [Pull Request](https://github.com/CHNZYX/Auto_Simulated_Universe/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

如题，比如我想用协议阈值6刷取，能不能有一个config可以更改？

**Comment by CHNZYX** [comment]
在actions/default.json中，删去第一项"折磨难度"的内容即可。具体删除内容为：
    {
        "name": "折磨难度",
        "trigger":{
            "text": "折磨难度",
            "box": [1081, 1173, 82, 112],
            "redundancy": 30
        },
        "actions":
        [
            {
                "position": [1529, 884]
            }
        ]
    },
