### ISSUE TITLE
[Bug]: 差分宇宙所有场景无法自动战斗，不过我找到了通用解决方法

### ISSUE THREAD

**Issue by yunshaochu** [CHNZYX/Auto_Simulated_Universe#312]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

V7.15

### 重现步骤

进入战斗时，所有战斗都不会触发自动战斗。不过我观察到，如果以0.1s的间隔不停点击自动战斗的'V'键，就能实现百分之百自动战斗。不过我不懂怎么修改代码进行pr，所以在此反馈

### 期望的结果是什么？

自动战斗

### 实际的结果是什么？

无法自动战斗

**Comment by shotamiao** [comment]
其实游戏里自带的默认自动战斗的选项勾选一下就行了，预计作者不会更新这个功能
