### ISSUE TITLE
[Bug]: 地图73927在游戏在显示的地图变了

### ISSUE THREAD

**Issue by Gaoxiang2002** [CHNZYX/Auto_Simulated_Universe#313]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

7.15

### 重现步骤

现在的地图样式如附件所示：
![init](https://github.com/user-attachments/assets/43fecbaf-180e-48cf-9263-5e3c51a48560)
程序中的地图样式为：
![init](https://github.com/user-attachments/assets/1d0b82be-4f56-4efe-a2c5-f2646c81b5b1)
这个地图改变应该是最近发生的，上周程序还在正常运行，现在到这个图，终端就提示找不到地图，我用我截的图片替换之后，终端提示可以识别到地图73927，走起来到拐弯的时候后本应该，但是走起来到拐弯的时候后就一直向右走，每次都会有问题，其它地图目前没有发现问题，好像只有这个地图，希望大佬可以修复bug，谢谢大佬❤️

### 期望的结果是什么？

正常跑图

### 实际的结果是什么？

跑图不正常

### 补充说明（可选）

感谢大佬的付出，这个是我用过最好的脚本，向大佬致以最崇高的敬意！

**Comment by zy32153** [comment]
我打的第八宇宙好像没有这个图，在bug修复之前可以试试看第八宇宙。（但是这个怎么看都像是星铁的bug...）

**Comment by CHNZYX** [comment]
地图bug一直是无法解决的问题，这也是自动化不支持第九世界的原因。
