### ISSUE TITLE
[Bug]: 无法正常启动差分宇宙，显示无法移动临时目录

### ISSUE THREAD

**Issue by weinojin** [CHNZYX/Auto_Simulated_Universe#319]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

7.15

### 重现步骤

打开程序，点击差分宇宙运行，第一次无反应，第二次点击后报错，并且无法正常关闭程序
![image](https://github.com/user-attachments/assets/c70e2a81-bd78-49eb-8da6-06c7e37bfd4d)

### 期望的结果是什么？

可以正常使用

### 实际的结果是什么？

可以正常进行校准，模拟宇宙，与差分宇宙均无法使用会报错

### 日志记录

INFO [2024-08-19 09:52:25,038] [admin.py:29] isUserAdmin - CheckTokenMembership returned: True
INFO [2024-08-19 09:52:25,044] [app.py:360] Assets path configured: C:\Users\wei\AppData\Local\Temp\_MEI213682\assets
INFO [2024-08-19 09:52:25,044] [flet_socket_server.py:62] Starting up TCP server on localhost:64900
INFO [2024-08-19 09:52:25,051] [app.py:173] Flet app has started...
INFO [2024-08-19 09:52:25,051] [app.py:133] App URL: tcp://localhost:64900
INFO [2024-08-19 09:52:25,052] [app.py:380] Starting Flet View app...
INFO [2024-08-19 09:52:25,059] [app.py:394] Flet View found in: C:\Users\wei\AppData\Local\Temp\_MEI213682\flet\bin\flet\flet.exe
INFO [2024-08-19 09:52:25,320] [app.py:237] App session started
WARNING [2024-08-19 09:52:37,278] [utils.py:104] 等待游戏窗口
INFO [2024-08-19 09:52:37,279] [utils.py:140] DPI: 2.25 A:1.02
INFO [2024-08-19 09:52:37,279] [utils.py:143] TEXT: 崩坏：星穹铁道
INFO [2024-08-19 09:52:37,997] [utils.py:35] 通知：初始计数：0  开始运行
INFO [2024-08-19 09:52:40,293] [diver.py:168] 触发 差分宇宙外:差分宇宙
WARNING [2024-08-19 09:53:01,245] [diver.py:85] 等待游戏窗口
WARNING [2024-08-19 09:53:12,755] [diver.py:85] 等待游戏窗口
WARNING [2024-08-19 09:53:15,958] [diver.py:85] 等待游戏窗口
WARNING [2024-08-19 09:53:17,810] [utils.py:104] 等待游戏窗口
INFO [2024-08-19 09:53:17,811] [utils.py:140] DPI: 2.25 A:1.02
INFO [2024-08-19 09:53:17,811] [utils.py:143] TEXT: 崩坏：星穹铁道
INFO [2024-08-19 09:53:18,324] [utils.py:35] 通知：初始计数：0  开始运行

### 补充说明（可选）

之前是可以正常使用的，感觉像是我自己电脑的问题，不过自己没有思路解决，幸苦大佬了~

**Comment by Xiaoqianghepipi** [comment]
win+R 输入%temp% 清理一下里面的文件与文件夹，这是系统的临时文件存放目录

**Comment by CHNZYX** [comment]
已经尝试在7.2中忽略错误

**Comment by weinojin** [comment]
辛苦大佬们了！
