### ISSUE TITLE
imgs\maps下添加分支

### ISSUE THREAD

**Issue by satisl** [CHNZYX/Auto_Simulated_Universe#32]
事实上该项目已经录入了很完整的地图信息，大多情况下都可以正常使用
但部分情况下，无法匹配到高相似度的地图，这时候就需要手动录入地图信息（实际上，录入的过程也很方便）
然而这存在一个问题，手动录入的地图信息和原有地图信息并没有区分开。这不方便版本间、玩家间的地图信息迁移。
比如我在v4.08下录入的地图信息，难以方便的迁移至v4.3版本。而我们也难以方便的共享自己录入的地图信息以及导入别人录入的地图信息。
所以，也许在imgs\maps上添加分支，比如项目自带的地图信息放在origin，而手动录入的地图信息可以自定义一个tag，又或者简单的哈希一个值是个好主意。

**Comment by CHNZYX** [comment]
地图分支https://github.com/CHNZYX/maps

**Comment by satisl** [comment]
也许我的描述有些问题
我的意思是，比如，以文件夹来进行分类
imgs\maps下存在一个origin文件夹，里面放着原有的地图文件
当我需要手动录入地图信息时，创建一个tag1文件夹来放置录入的文件信息
如此，当更新时，只需要更新origin文件夹而不影响手动录入的地图信息，亦或者直接移动tag1文件夹至新脚本来导入手动录入的地图信息
以及，当和他人共享，亦或者使用别人共享的地图信息时，仅需要传输对应的文件夹tag1
也不一定是文件夹，但如果能实现像描述中这种即插即用的感觉应该会不错

**Comment by CHNZYX** [comment]
如果录制了原有地图集中没用的新图，可以在maps仓库提pr。我认为在更新世界7前，多个地图分支是没有必要的，整合在一起是更方便的选择。

**Comment by CHNZYX** [comment]
新版本优化了录图，现在新图文件夹名有前缀my_，更新地图时若不勾选强制更新也不会抹除录制的新图了。不过还是建议录制、测试后将优质的新图去掉my_前缀并在maps仓库中提pr。
