### ISSUE TITLE
[Bug]: 老地图‘收容舱段’识别出问题了

### ISSUE THREAD

**Issue by kotoricon** [CHNZYX/Auto_Simulated_Universe#327]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

2.2

### 重现步骤

这个图以前记得没问题的，现在也识别不了了一小时内看见三次在这转圈无限重开几次了
![20240925124238](https://github.com/user-attachments/assets/e6fa8e11-c2b0-4bc7-9290-21d009712f09)
![20240925124956](https://github.com/user-attachments/assets/4369b983-609c-4080-bfc2-f31684419469)
![20240925124932](https://github.com/user-attachments/assets/22ce5d95-5df6-4644-ba2e-39138113dc33)

### 期望的结果是什么？

fix

### 实际的结果是什么？

fix

**Comment by fanjianlong123** [comment]
+ 1

**Comment by CHNZYX** [comment]
这是游戏的小地图bug，修不了
