### ISSUE TITLE
祝福丢弃事件卡住

### ISSUE THREAD

**Issue by vruses** [CHNZYX/Auto_Simulated_Universe#36]
在遇到第11层虚构史学家事件时，会卡在丢弃祝福这一步中，忘截图了。

**Comment by CHNZYX** [comment]
丢弃奇物分为两步：选择奇物，点击确认。请问还记得卡在哪里吗？当时是否已经选择了奇物，有几个待选奇物？

**Comment by vruses** [comment]
> 丢弃奇物分为两步：选择奇物，点击确认。请问还记得卡在哪里吗？当时是否已经选择了奇物，有几个待选奇物？

不是奇物，是祝福，一共 3 个待选祝福，当时没有选择祝福。不好意思，刚查了一下好像叫焚化工事件，就是丢弃一个 1 星祝福选择一个 1-3 星祝福，类似这张图
![N`}1L~IN4)W~XGP4B%5D~`9](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/92210103/ee00ad11-3ca3-44f3-a283-48f90a108d31)

**Comment by CHNZYX** [comment]
好的，没有遇到过这个事件，我想想办法

**Comment by vruses** [comment]
遇到了，是这个事件：

![1685865959338](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/92210103/aae40c87-7def-4d67-bd69-7b550f109e34)


此时并不会选择要丢弃的祝福，当我尝试移动鼠标时，鼠标会自动归还到图片下方所标记的位置

![1685866326218](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/92210103/c2a6cdf8-d5ed-453c-9e7c-de2e633f78d4)

**Comment by CHNZYX** [comment]
能否提供1920*1080的截图？会考虑增加这个功能

**Comment by vruses** [comment]
已更改为1920*1080分辨率截图

**Comment by CHNZYX** [comment]
好的，现在的策略是选中间那个丢弃。

**Comment by 7890qwaszx** [comment]
可以改进为选择不感兴趣，或者丢弃非设置里面选定的命途的祝福

**Comment by CHNZYX** [comment]
暂时不考虑优化，收益实在不高。
