### ISSUE TITLE
关于提高队伍容错率

### ISSUE THREAD

**Issue by 246182606** [CHNZYX/Auto_Simulated_Universe#37]
1.进入休整区域后，远程角色空A一下，打破恢复血瓶，回复队伍血量
2.进入休整区域后，倘若队伍有角色死亡（角色死亡背景色变灰，不显示血条）直接点击复活装置进行复活
亦或者直接点击复活装置，如果显示角色头像，点击复活
PS：本人是代码小白，一点小建议，感谢大佬制作的工具
![584_2023042745134237](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/4770b144-4fa5-489c-b476-c440b11cf3f0)

![584_2023042745134185](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/75273392-6bba-43d3-a62d-0e1ccfaa44f6)

**Comment by CHNZYX** [comment]
已增加最后一关前打血瓶的功能，周日更新4.5版本。复活功能暂不考虑，最终boss之前不该有角色死亡，请调整配队。
