### ISSUE TITLE
雅利安六号地图迷路

### ISSUE THREAD

**Issue by JINXIETY** [CHNZYX/Auto_Simulated_Universe#38]
打模拟世界5难度二的时候发现的，在进入雅利安六号所在地图时，打完怪物有一定概率迷路，会自己选择退出
![1685852126049](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/124946759/7c2ac6dc-0b42-440a-8e37-b58959dd7234)

**Comment by CHNZYX** [comment]
没有完全支持世界五，参见README

**Comment by JINXIETY** [comment]
好的谢谢您

**Comment by 7890qwaszx** [comment]
根据README，模拟四地图基本录入完成，但该issue截图中的地图在模拟四也出现了，同样会迷路
