### ISSUE TITLE
匹配图标/识别地图功能会在部分场合失效

### ISSUE THREAD

**Issue by GOJiong** [CHNZYX/Auto_Simulated_Universe#39]
校准后开始运行，但是在第二步就会卡住（选择宇宙的难度页面），无限返回“匹配不到任何图标”。

[states.py:418] 匹配不到任何图标

这里通过手动点击开始/手动选择角色，强行进入模拟宇宙关卡后，角色基本可以自动执行至第一个精英处，但是在打掉第一个精英后会有大概率卡在沉浸奖励的对话框那里，由于会先自动点击对话框，然后就在沉浸奖励的选择页面卡住，此时依然会无限返回“匹配不到任何图标”。

具体可见log文件

[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11648077/log.txt)

**Comment by CHNZYX** [comment]
游戏界面是否被遮挡？比如温度监控之类的小部件。沉浸奖励不会选择，是否使用的是最新版本？

**Comment by GOJiong** [comment]
> 游戏界面是否被遮挡？比如温度监控之类的小部件。沉浸奖励不会选择，是否使用的是最新版本？

不好意思，看起来是我自己电脑的问题，电脑本身的分辨率也必须和游戏内一样为1920x1080才行，改了下设置之后问题已经解决了
