### ISSUE TITLE
建议优化祝福选取

### ISSUE THREAD

**Issue by a-small-monster** [CHNZYX/Auto_Simulated_Universe#41]
建议在选不到对应命途祝福时，增加一个优先级选项。比如打第6世界，记忆是打boss完全没用的祝福，虚无（除了弱点击破）和欢愉如果没有对应角色，效果依然很低，存护/毁灭/丰饶比较通用。

**Comment by CHNZYX** [comment]
自动化并不只是面向世界6开发的，会考虑适当增加优先级

**Comment by CHNZYX** [comment]
已更新
