### ISSUE TITLE
沉浸器、复活装置误触卡死

### ISSUE THREAD

**Issue by gongfuture** [CHNZYX/Auto_Simulated_Universe#44]
如题，有时会跑到这俩玩意边上（当然也有下载装置，但是一般够下载一个人所以不会卡死），依旧会触发F，导致程序卡在复活选择页面或者沉浸领取页面
或许可以针对这几个的文本识别增添黑名单或者条件？

**Comment by CHNZYX** [comment]
版本更新后ui改变，正在修复

**Comment by CHNZYX** [comment]
已更新
