### ISSUE TITLE
(-5:Bad argument) in function 'cvtColor'

### ISSUE THREAD

**Issue by makcimbx** [CHNZYX/Auto_Simulated_Universe#45]
Some problem with openCV, maybe because of the version, not sure.
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/10184529/6fa88190-d611-4818-9029-4fc8c7367b03)

**Comment by makcimbx** [comment]
If i comment this lines, this method working fine.
```
if self.full:
self.screen_raw[:-11, :-11] = self.screen_raw[11:, 11:]
```

**Comment by CHNZYX** [comment]
updated
