### ISSUE TITLE
'charmap' codec can't encode characters in position 3-6: character maps to <undefined>

### ISSUE THREAD

**Issue by makcimbx** [CHNZYX/Auto_Simulated_Universe#46]
The error when writing to a file, was solved by adding an encoding to all file opening functions.
Example:
`with open('logs/notif.txt','w', encoding="gb2312") as fh:`

**Comment by CHNZYX** [comment]
Not sure the latest release has this problem. You can test it

**Comment by makcimbx** [comment]
Still have this error on latest main 
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/10184529/d545b588-1d20-469d-bdc8-803786bcd460)

**Comment by CHNZYX** [comment]
Maybe it's because your computer doesn't have Chinese font packs. if "gb2312" works, you can use it.

**Comment by CHNZYX** [comment]
fixed
