### ISSUE TITLE
计数通知不生效

### ISSUE THREAD

**Issue by Asakushen** [CHNZYX/Auto_Simulated_Universe#48]
本地远程桌面开启gui
主桌面开启notif
notif不计数以下是日志
[log_2023-06-09-17-35.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11705185/log_2023-06-09-17-35.txt)
[notif.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11705188/notif.txt)
[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11705213/log.txt)

**Comment by CHNZYX** [comment]
已更新
