### ISSUE TITLE
[功能请求] 强制前台功能

### ISSUE THREAD

**Issue by Aniverse** [CHNZYX/Auto_Simulated_Universe#49]
有时候挂机的时候弹出什么弹窗之类的会把游戏窗口的前台抢走，此时程序就停了；或者用一些远程桌面软件连接（比如向日葵）也可能抢前台。  

强制前台和断点回复功能是冲突的，因此有些人不需要这个功能；但对于我外出或者晚上睡觉挂机这种场合是不需要断点回复的。  
鉴于现在有 GUI 了，能否考虑在 GUI 或者配置文件里加个选项，或者某个快捷键来控制是否打开强制前台功能？  

两种实现方式，一种是用快捷键开关是否强制前台，另一种是打开了强制前台后，如果检测到游戏没在前台，则每过一定时间（比如说 20 秒）把游戏切到前台

**Comment by CHNZYX** [comment]
每隔十分钟会执行，太高频担心出bug后影响正常使用
