### ISSUE TITLE
遇到事件“阮·梅”时，脚本选择了2000碎片

### ISSUE THREAD

**Issue by bf109f4** [CHNZYX/Auto_Simulated_Universe#51]
大佬能不能给优化一下orz

**Comment by CHNZYX** [comment]
概率过低，你可以遇到的时候截图保存为jpg发出来

**Comment by weiby3** [comment]
我也遇到了，后面发现完成了成就才意识到的，估计他也一样

**Comment by FiiiiVe** [comment]
![QQ图片20230613204552](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/28562265/17ce17d3-1151-47c7-9138-4cdeac0872af)

**Comment by CHNZYX** [comment]
已经收到，谢谢。会在下个版本更新
