### ISSUE TITLE
打开调试模式到—，仍然会在12层或13层自动结算退出

### ISSUE THREAD

**Issue by z134git** [CHNZYX/Auto_Simulated_Universe#52]
INFO [2023-06-10 14:17:38,609] [utils.py:226] 匹配到图片 ./imgs/f.jpg 相似度 0.989913 阈值 0.970000
INFO [2023-06-10 14:17:39,330] [utils.py:226] 匹配到图片 ./imgs/f.jpg 相似度 0.988069 阈值 0.970000
INFO [2023-06-10 14:17:39,332] [utils.py:226] 匹配到图片 ./imgs/tele.jpg 相似度 0.984512 阈值 0.965000
INFO [2023-06-10 14:17:39,332] [states.py:254] 地图-1已完成,相似度-1,进入13层
DEBUG [2023-06-10 14:17:39,336] [utils.py:114] 按下按钮 f，等待 0 秒后释放
DEBUG [2023-06-10 14:17:40,343] [utils.py:114] 按下按钮 1，等待 0 秒后释放
DEBUG [2023-06-10 14:17:42,076] [utils.py:114] 按下按钮 esc，等待 0 秒后释放
F8 已被按下，尝试停止运行
INFO [2023-06-10 14:17:44,487] [states.py:606] 尝试停止运行
INFO [2023-06-10 14:17:45,132] [states.py:354] 通关！当前层数:1
INFO [2023-06-10 14:17:45,837] [states.py:130] 停止运行

**Comment by CHNZYX** [comment]
已更新，调试模式为√时不会在打boss前结算退出
