### ISSUE TITLE
希望能有优先战斗层的设置

### ISSUE THREAD

**Issue by Anyk00** [CHNZYX/Auto_Simulated_Universe#53]
现在的打法很容易到最后一层还凑不齐两个回响，希望能尽量多走战斗凑够回响。
以及希望能出奇物黑名单功能，例如在巡猎命途下不选其他命途的火漆。

**Comment by CHNZYX** [comment]
不考虑奇物黑名单。关于传送点选择目前是随机，之后可能会优化
