### ISSUE TITLE
下载报错（病毒）

### ISSUE THREAD

**Issue by wmd-1** [CHNZYX/Auto_Simulated_Universe#57]
如下面两图，Windows无法下载
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/65806693/2cfa4880-debb-424a-a1e5-7a083438423f)
![微信图片_20230611143042](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/65806693/d5650018-cfd6-4ec2-84cb-d3ca090f3049)

**Comment by CHNZYX** [comment]
这是远程桌面的修改文件，不属于本项目，请酌情下载使用。
