### ISSUE TITLE
請問要如何後台運行

### ISSUE THREAD

**Issue by mykey8585** [CHNZYX/Auto_Simulated_Universe#59]
請問要如何後台運行

**Comment by CHNZYX** [comment]
https://github.com/CHNZYX/Auto_Simulated_Universe/blob/main/utils/%E6%9C%AC%E5%9C%B0%E5%A4%9A%E7%94%A8%E6%88%B7%E8%BF%9C%E7%A8%8B%E7%99%BB%E9%99%86.7z
里面有详细教程

**Comment by yutouyes** [comment]
> https://github.com/CHNZYX/Auto_Simulated_Universe/blob/main/utils/%E6%9C%AC%E5%9C%B0%E5%A4%9A%E7%94%A8%E6%88%B7%E8%BF%9C%E7%A8%8B%E7%99%BB%E9%99%86.7z 里面有详细教程

后续版本删除这套工具了，请问是出了什么问题嘛
