### ISSUE TITLE
校准时出现报错，无法将浮点数无穷大转换为整数（OverflowError: cannot convert float infinity to integer）

### ISSUE THREAD

**Issue by yukiime** [CHNZYX/Auto_Simulated_Universe#61]
F:\Auto_Simulated_Universe>python align_angle.py
INFO [2023-06-12 13:31:47,430] [align_angle.py:30] 开始校准
WARNING [2023-06-12 13:31:47,436] [utils.py:77] 等待游戏窗口
[0]
F:\Auto_Simulated_Universe\align_angle.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  su.multi *= ax / ay
Traceback (most recent call last):
  File "F:\Auto_Simulated_Universe\align_angle.py", line 81, in <module>
    main()
  File "F:\Auto_Simulated_Universe\align_angle.py", line 42, in main
    su.mouse_move(60)
  File "F:\Auto_Simulated_Universe\utils\utils.py", line 903, in mouse_move
    dx = int(9800 * y * 1295 / self.real_width / 180 * self.multi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: cannot convert float infinity to integer

--------
报错时
x: 60
y: 30
self.real_width: 1920
dx: inf

--------
显示器分辨率：2560x1440
游戏分辨率：1920x1080（窗口模式）

**Comment by CHNZYX** [comment]
需要管理员权限

**Comment by yukiime** [comment]
> 需要管理员权限

使用管理员运行后，仍然有这个问题，报错如上一致。
但现在这个问题暂时解决了，应该是我使用了扩展显示器导致了这个问题，抱歉。
现在我只使用一个显示器，未修改其他参数，可以成功运行。
