### ISSUE TITLE
地图代码99570不识别问题

### ISSUE THREAD

**Issue by UserAzhuO** [CHNZYX/Auto_Simulated_Universe#62]

**Comment by CHNZYX** [comment]
小概率事件？

**Comment by 246182606** [comment]
![2023-06-21_005923](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/dae45af8-efa6-477c-b635-a83fe1395387)
![2023-06-21_005935](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/9cd61835-9a34-4166-8738-68af9aa55d64)
地图编号：99750
描述：打完第一个怪后，角色开始行走（视角转动过大），一直卡在楼梯这，暂离返回依旧复现
ps:不知道怎么上传视频，录了一段
