### ISSUE TITLE
模拟宇宙4难度三报错

### ISSUE THREAD

**Issue by nizuowanzhenbang** [CHNZYX/Auto_Simulated_Universe#63]
INFO [2023-06-12 23:51:18,625] [align_angle.py:76] 校准完成
WARNING [2023-06-12 23:51:25,685] [utils.py:77] 等待游戏窗口
INFO [2023-06-12 23:51:27,000] [states.py:62] 加载地图
INFO [2023-06-12 23:51:27,594] [states.py:68] 加载地图完成，共 47 张
INFO [2023-06-12 23:51:27,719] [utils.py:227] 匹配到图片 ./imgs/f.jpg 相似度 0.992240 阈值 0.970000
INFO [2023-06-12 23:51:28,538] [utils.py:227] 匹配到图片 ./imgs/f.jpg 相似度 0.992249 阈值 0.970000
0.8487523794174194
DEBUG [2023-06-12 23:51:28,545] [utils.py:115] 按下按钮 f，等待 0 秒后释放
INFO [2023-06-12 23:51:29,535] [states.py:512] 匹配不到任何图标
INFO [2023-06-12 23:51:30,607] [utils.py:227] 匹配到图片 ./imgs/init.jpg 相似度 0.996731 阈值 0.955000
INFO [2023-06-12 23:51:32,201] [utils.py:227] 匹配到图片 ./imgs/begin.jpg 相似度 0.996317 阈值 0.970000
INFO [2023-06-12 23:51:34,619] [utils.py:227] 匹配到图片 ./imgs/start.jpg 相似度 0.983151 阈值 0.970000
INFO [2023-06-12 23:51:36,212] [utils.py:227] 匹配到图片 ./imgs/yes.jpg 相似度 0.998937 阈值 0.970000
INFO [2023-06-12 23:51:37,811] [states.py:512] 匹配不到任何图标
INFO [2023-06-12 23:51:38,885] [utils.py:227] 匹配到图片 ./imgs/fate.jpg 相似度 0.983170 阈值 0.955000
INFO [2023-06-12 23:51:40,474] [utils.py:227] 匹配到图片 ./imgs/fate_2.jpg 相似度 0.994509 阈值 0.970000
INFO [2023-06-12 23:51:42,078] [states.py:512] 匹配不到任何图标
INFO [2023-06-12 23:51:43,156] [states.py:512] 匹配不到任何图标
INFO [2023-06-12 23:51:44,239] [states.py:512] 匹配不到任何图标
INFO [2023-06-12 23:51:48,446] [states.py:337] 地图编号：89201  相似度：0.546031746031746
E: 运行函数时出现错误
Traceback (most recent call last):
  File "gui\choose.py", line 31, in run
  File "states.py", line 698, in start
  File "states.py", line 116, in route
  File "states.py", line 346, in normal
FileNotFoundError: [Errno 2] No such file or directory: 'check0.txt'

**Comment by CHNZYX** [comment]
关闭调试模式，这个问题下个版本会修复
