### ISSUE TITLE
地图99570经常卡住

### ISSUE THREAD

**Issue by weiby3** [CHNZYX/Auto_Simulated_Universe#66]
如图，经常见到一直卡在这里跑。
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/30197106/88ad2fd7-5019-4682-a7dc-d8a4b735e22f)
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/30197106/dcfd5a6d-366f-4c3a-bc61-3e4034749dbc)

附日志
[log.zip](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11727305/log.zip)

**Comment by lyb12358** [comment]
99570确实一直卡住

**Comment by CHNZYX** [comment]
用的是哪个版本？

**Comment by weiby3** [comment]
release中的4.84

**Comment by sunlcy** [comment]
我也是这里卡住 4.86版本  标记的路径点好像并没有起作用

**Comment by CHNZYX** [comment]
在我的测试中，已经校准的状态下一般不会迷路。所以有可能是忘记校准了，出现问题的可以试试重新校准。

**Comment by a-small-monster** [comment]
+1，这张图卡麻了，一开始卡住以为没做这张图，自己加了以后，测试时候过了，第二次碰到又卡住了，要么卡桥左边的，要么卡右边题主这个位置

**Comment by CHNZYX** [comment]
暂未遇到这个问题，遇到问题可以考虑更新版本
