### ISSUE TITLE
希望能增加优先选择未收录图鉴的祝福

### ISSUE THREAD

**Issue by sssssoviet** [CHNZYX/Auto_Simulated_Universe#67]
可以弄成一个可选模式

**Comment by CHNZYX** [comment]
会考虑增加，但是优先级较低，可能近段时间不会更新这项功能

**Comment by CHNZYX** [comment]
事实上，难以获得的祝福都有前置祝福，因此用不同流派都打几次就能解锁完全。现在所有流派的祝福已经优化完成，可以使用了。因此这个功能不需要特意增加
