### ISSUE TITLE
 地图18769匹配失败

### ISSUE THREAD

**Issue by Jacheers** [CHNZYX/Auto_Simulated_Universe#71]
地图如下：
![capture_20230614054915740](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/61894695/8f9dc0c5-c07c-4b27-9b97-a6852d3e2377)

总是会匹配到其他地图（每次都不一样），我把其他地图移除之后，只留下18769，发现匹配率只有0.36

log文件：
[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11739806/log.txt)

**Comment by Jacheers** [comment]
这是18769的图片：  
![{{)U07J%0V6J Z8GN(LL}%0](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/61894695/fc061ee4-58f6-443e-86d6-f3e75f2d187e)

这是游戏实况图片：   
![~{1S`AXO}M`UGJ6WA(F~RYU](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/61894695/987840f8-8074-4de7-8a02-eec956a8a55a)

感觉匹配率0.36不是没有原因的。我的光照质量开的是中。应该是够用的。   
估计是游戏更新导致的问题，大佬有空重新截一下图吧。

**Comment by Jacheers** [comment]
还有就是我选存护命途的时候，我看到bless文件夹下面是有关于存护的优化的。但实际上却总是优先选择琥珀盾，而不是bless文件夹里的echo1，echo2。关于这点还请大佬帮忙检查一下

**Comment by CHNZYX** [comment]
新版本应该已经修复
