### ISSUE TITLE
难度4的模拟宇宙3中在第一个精英怪关卡中不会主动攻击精英怪，且会在攻击关底boss前退出

### ISSUE THREAD

**Issue by wwwwwwby** [CHNZYX/Auto_Simulated_Universe#73]
难度4的模拟宇宙3第一个精英怪关卡中，极大概率会识别不到怪物，不进行攻击，导致循环卡死。
表现是已经锁定到怪物，屏幕上方已经出现怪物名字以及“Z”字母。但是并没有识别到Z并攻击。

此外，还会出现在关底直接退出的情况。

希望大佬尽快修复，万分感谢！

**Comment by CHNZYX** [comment]
仔细阅读README，现在只有宇宙6稳定。没有识别到可能是因为识别范围太小，你可以参与录图，加速其他宇宙的适配进程。
