### ISSUE TITLE
希望能添加一个奶妈位强制开大的选项

### ISSUE THREAD

**Issue by raincamus1998** [CHNZYX/Auto_Simulated_Universe#74]
奶妈经常能量满了但因为血量较为健康不开大，这样容易被蓄力一招带走，或者残血。让奶妈能量一满就开大可以显著增加模拟宇宙BOSS战容错率（奶妈充能都挺快的）。方法：比如奶妈在1号位，那可以每隔20秒输入一次键位1。

**Comment by heng-ke** [comment]
本脚本主要解决模拟宇宙跑图的正常流程，添加一个20秒输入1的定时器或者循环较为浪费性能，战局控制属于自动战斗功能的范畴。若脚本完善后可能会考虑添加此功能

**Comment by CHNZYX** [comment]
已增加随机开大功能

**Comment by raincamus1998** [comment]
> 本脚本主要解决模拟宇宙跑图的正常流程，添加一个20秒输入1的定时器或者循环较为浪费性能，战局控制属于自动战斗功能的范畴。若脚本完善后可能会考虑添加此功能

理解理解，那我自己加个识图点击吧

**Comment by raincamus1998** [comment]
> 已增加随机开大功能

感谢

**Comment by a-small-monster** [comment]
虽然感觉有点不识好歹，但想问问作者，随机开大的代码是战斗界面代码那块的self.press(str(random.randint(1，4)))吗？因为我发现好几次奶大好了就放，导致boss放大后都没大回血了

**Comment by CHNZYX** [comment]
功能已经弃用
