### ISSUE TITLE
地图被错误识别为89358

### ISSUE THREAD

**Issue by happygaoxiao** [CHNZYX/Auto_Simulated_Universe#75]
`地图编号：89358  相似度：0.40061162079510704`
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/24514908/ac452723-fbde-440f-b351-2c116ef1e59d)

这张图每次都会识别错误，导致卡在原地转圈

**Comment by CHNZYX** [comment]
这是层数识别错误导致的，暂离可恢复。层数识别正在优化
