### ISSUE TITLE
优先奇物建议

### ISSUE THREAD

**Issue by a-small-monster** [CHNZYX/Auto_Simulated_Universe#77]
在选用巡猎命途的时候，个人觉得博士之袍和巡猎火漆应该是最高优先级，其次是降维骰子和福灵胶，按照原代码字典形式遍历的结果是反过来的，建议可以改成列表或者有序字典形式？
另外还有一个建议不知道能不能实现，按照我的理解，如果选了某个命途，那么其他命途的火漆应该是最低优先级

**Comment by CHNZYX** [comment]
已经实现
