### ISSUE TITLE
脚本不能正常运行

### ISSUE THREAD

**Issue by mintsflandre** [CHNZYX/Auto_Simulated_Universe#79]
测试了模拟宇宙6与4，有以下问题：
1.在迷路情况下不会点击直接结算，而是会点击暂离，与说明中描述不符
2.到第二个精英怪时必定不会攻击，只会跑来跑去触发迷路
3.建议增加判断屏幕内红圈与怪物姓名条避免不攻击怪的错误

**Comment by CHNZYX** [comment]
大概率暂离小概率结算。
暂时没有遇到，之后会修复
屏幕内干扰较大，识别红圈难度很大

**Comment by CHNZYX** [comment]
2已经修复，下个打包版本会更新
