### ISSUE TITLE
关于环境配置问题

### ISSUE THREAD

**Issue by esdrtf** [CHNZYX/Auto_Simulated_Universe#8]
“只支持1920*1080(窗口化或全屏幕)，关闭HDR。”

不太清奇HDR具体指带什么，是设置中的某一项吗？
请求更多信息，

**Comment by omg-xtao** [comment]
https://support.microsoft.com/zh-cn/windows/%E5%9C%A8-windows-%E4%B8%8A%E6%B5%81%E5%BC%8F%E4%BC%A0%E8%BE%93-hdr-%E8%A7%86%E9%A2%91-2e98fc86-5358-d6bc-1e22-d0e416d3c704#WindowsVersion=Windows_11

**Comment by esdrtf** [comment]
感谢大佬
