### ISSUE TITLE
安装环境依赖报错，希望查一下什么情况，群里也有几位是一样的，我重装Python都不行

### ISSUE THREAD

**Issue by i-cecreamer** [CHNZYX/Auto_Simulated_Universe#82]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/128817713/ca774449-b204-4642-932e-1c8899becabe)

**Comment by CHNZYX** [comment]
ppocr不支持3.11以上的python版本，你可以用虚拟环境安装

**Comment by i-cecreamer** [comment]
> ppocr不支持3.11以上的python版本，你可以用虚拟环境安装

pip install ppocr-onnx，我自己运行了这条代码安装就可以了，而且群里的py是3.11，最好可以注明一下吧

**Comment by wizardt** [comment]
态度极为生硬
