### ISSUE TITLE
本周版本突然卡进入模拟宇宙界面直接与黑塔对话

### ISSUE THREAD

**Issue by nyano** [CHNZYX/Auto_Simulated_Universe#83]
设置：速通模式 不知道有没有影响

我看了下日志，不知道为啥就开始校准，我也没移动鼠标，不知道为啥要等待游戏窗口了。。然后我默认角色是4号位娜塔莎，卡住状态换了角色是1号位瓦尔特了，但是我没按键换角色啊
手动调整到模拟宇宙F，仍不点击，仍提示匹配不到任何图标，然后直接往黑塔身上跑，然后继续跟黑塔聊天
似乎暂离后-开始校准-跑到了黑塔边上-然后直接点了F

已经多次了，不是小概率事件
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/5079651/2ca6393c-2a5b-4fbe-8ad2-d9569d6b77d6)

INFO [2023-06-19 21:48:32,818] [utils.py:234] 匹配到图片 ./imgs/event.jpg 相似度 0.981137 阈值 0.970000
ERROR [2023-06-19 21:49:27,465] [states.py:356] 地图-1未发现目标,相似度-1，尝试暂离
INFO [2023-06-19 21:49:28,037] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:28,693] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:29,389] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:30,472] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:31,146] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:31,815] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:32,847] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.991332 阈值 0.970000
INFO [2023-06-19 21:49:33,351] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.993037 阈值 0.970000
INFO [2023-06-19 21:49:35,032] [align_angle.py:30] 开始校准
WARNING [2023-06-19 21:49:35,298] [utils.py:82] 等待游戏窗口
INFO [2023-06-19 21:49:42,389] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.991498 阈值 0.970000
INFO [2023-06-19 21:49:42,910] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.991514 阈值 0.970000
INFO [2023-06-19 21:49:43,669] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:44,317] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:44,967] [states.py:461] 匹配不到任何图标
INFO [2023-06-19 21:49:46,031] [states.py:461] 匹配不到任何图标

**Comment by CHNZYX** [comment]
更新版本了吗？github上还没发布最新打包版本，但是群里有

**Comment by nyano** [comment]
呜呜呜 我是20点的版本，我再更新试试

**Comment by sunlcy** [comment]
> 更新版本了吗？github上还没发布最新打包版本，但是群里有

现在GitHub上这个最新版本确实会这样  我也遇到了  没开速通  我又退回去用老版本了  而且战斗里随机按1234设置个选项吧

**Comment by sunlcy** [comment]
4.9free这个

**Comment by nyano** [comment]
确实喵。21:00的最新版本，刚又遇到了

INFO [2023-06-19 22:43:31,131] [utils.py:844] 进入新地图或者进入战斗 59.53173692099891
ERROR [2023-06-19 22:43:35,496] [states.py:357] 地图67673未发现目标,相似度0.7037861915367484，尝试暂离
INFO [2023-06-19 22:43:36,047] [states.py:462] 匹配不到任何图标
INFO [2023-06-19 22:43:36,716] [states.py:462] 匹配不到任何图标
INFO [2023-06-19 22:43:37,371] [states.py:462] 匹配不到任何图标
INFO [2023-06-19 22:43:38,468] [states.py:462] 匹配不到任何图标
INFO [2023-06-19 22:43:39,123] [states.py:462] 匹配不到任何图标
INFO [2023-06-19 22:43:39,798] [states.py:462] 匹配不到任何图标
INFO [2023-06-19 22:43:43,213] [states.py:290] 地图编号：23480  相似度：0.28054298642533937
INFO [2023-06-19 22:43:43,747] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.993026 阈值 0.970000
INFO [2023-06-19 22:43:44,253] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.993022 阈值 0.970000
INFO [2023-06-19 22:43:45,949] [align_angle.py:30] 开始校准
WARNING [2023-06-19 22:43:46,234] [utils.py:82] 等待游戏窗口
INFO [2023-06-19 22:43:52,571] [states.py:290] 地图编号：23480  相似度：0.248868778280543
INFO [2023-06-19 22:43:55,556] [states.py:290] 地图编号：23480  相似度：0.25339366515837103
INFO [2023-06-19 22:43:58,526] [states.py:290] 地图编号：23480  相似度：0.2398190045248869
INFO [2023-06-19 22:44:01,454] [states.py:290] 地图编号：23480  相似度：0.26244343891402716
INFO [2023-06-19 22:44:04,361] [states.py:290] 地图编号：46900  相似度：0.23868312757201646
INFO [2023-06-19 22:44:07,353] [states.py:290] 地图编号：23480  相似度：0.25339366515837103
INFO [2023-06-19 22:44:10,327] [states.py:290] 地图编号：12872  相似度：0.2384937238493724
INFO [2023-06-19 22:44:13,252] [states.py:290] 地图编号：12872  相似度：0.2301255230125523
INFO [2023-06-19 22:44:16,105] [states.py:290] 地图编号：23480  相似度：0.2669683257918552
INFO [2023-06-19 22:44:19,051] [states.py:290] 地图编号：23480  相似度：0.22624434389140272
INFO [2023-06-19 22:44:22,017] [states.py:290] 地图编号：12872  相似度：0.25523012552301255
INFO [2023-06-19 22:44:24,939] [states.py:290] 地图编号：23480  相似度：0.2669683257918552
INFO [2023-06-19 22:44:27,819] [states.py:290] 地图编号：46900  相似度：0.25102880658436216
INFO [2023-06-19 22:44:30,723] [states.py:290] 地图编号：23480  相似度：0.23076923076923078
INFO [2023-06-19 22:44:33,661] [states.py:290] 地图编号：12872  相似度：0.23430962343096234
INFO [2023-06-19 22:44:36,649] [states.py:290] 地图编号：68145  相似度：0.2892561983471074

**Comment by CHNZYX** [comment]
下个版本会取消自动校准
