### ISSUE TITLE
迷路后请直接结算！

### ISSUE THREAD

**Issue by Jacheers** [CHNZYX/Auto_Simulated_Universe#84]
[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11795268/log.txt)

我觉得什么大概率暂离，小概率结算是不可接受的。

这个程序从凌晨4点磨叽到10点半都是同一张地图。

**Comment by hanuxxx** [comment]
直接结算会损失奖励的，一周拿奖励的次数就这么多

**Comment by Jacheers** [comment]
起码提供一个结算的选项。而且一次才损失几个绿狗粮，真不在乎。程序发呆一晚上更亏

**Comment by 7890qwaszx** [comment]
希望作者能够把这些细节选项做成开关，让使用者自己设置

**Comment by CHNZYX** [comment]
抱歉，这是因为一个bug，现已修复。
