### ISSUE TITLE
在进入某些事件时，卡在界面上没有响应，直到手动点一下鼠标

### ISSUE THREAD

**Issue by bf109f4** [CHNZYX/Auto_Simulated_Universe#85]
这是当时的日志：

INFO [2023-06-20 20:53:22,948] [states.py:211] 识别到传送点
INFO [2023-06-20 20:53:24,870] [states.py:229] 地图30797已完成,相似度0.5094339622641509,进入7层
INFO [2023-06-20 20:53:26,091] [utils.py:535] 交互点相似度0.9461984634399414，位置120,68
事件
INFO [2023-06-20 20:53:35,184] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.991425 阈值 0.970000
INFO [2023-06-20 20:53:35,698] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.989928 阈值 0.970000
WARNING [2023-06-20 20:53:50,745] [states.py:99] 等待游戏窗口
INFO [2023-06-20 20:55:02,589] [utils.py:234] 匹配到图片 ./imgs/event.jpg 相似度 0.978471 阈值 0.970000
INFO [2023-06-20 20:55:03,931] [utils.py:234] 匹配到图片 ./imgs/event.jpg 相似度 0.977455 阈值 0.970000
INFO [2023-06-20 20:55:05,221] [utils.py:234] 匹配到图片 ./imgs/event.jpg 相似度 0.978385 阈值 0.970000
INFO [2023-06-20 20:55:06,534] [utils.py:234] 匹配到图片 ./imgs/event.jpg 相似度 0.980013 阈值 0.970000
INFO [2023-06-20 20:55:07,814] [utils.py:234] 匹配到图片 ./imgs/event.jpg 相似度 0.979952 阈值 0.970000
INFO [2023-06-20 20:55:07,932] [utils.py:234] 匹配到图片 ./imgs/arrow.jpg 相似度 0.998686 阈值 0.970000
INFO [2023-06-20 20:55:08,907] [utils.py:234] 匹配到图片 ./imgs/event.jpg 相似度 0.980470 阈值 0.970000
INFO [2023-06-20 20:55:09,247] [utils.py:234] 匹配到图片 ./imgs/star.jpg 相似度 0.986152 阈值 0.965000

卡了快2分钟我才注意到

**Comment by CHNZYX** [comment]
哪个事件？

**Comment by bf109f4** [comment]
很多事件都有
我是双屏玩家，感觉进入事件时他把鼠标往屏外挪了一下然后强制点击切屏，导致了不正常的暂停。
我把另一个屏幕掐掉了，就一切正常了。
不知道这个bug能不能处理一下。。。不然没法用了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月20日(周二) 晚上10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CHNZYX/Auto_Simulated_Universe] 在进入某些事件时，卡在界面上没有响应，直到手动点一下鼠标 (Issue #85)




 
哪个事件？

**Comment by CHNZYX** [comment]
修不了，我没有双屏。建议开多用户远程控制
