### ISSUE TITLE
地图99570，角色未按照预定路线行走

### ISSUE THREAD

**Issue by 246182606** [CHNZYX/Auto_Simulated_Universe#86]
地图编号：99750
描述：打完第一个怪后，角色开始行走（视角转动过大），一直卡在楼梯这，暂离返回依旧复现
每次进这个场景都会卡楼梯右角，最新版本，看到其他人也遇到过这个情况
![2023-06-21_005935](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/d37fc542-1550-4fff-b215-248c94492ade)
![2023-06-21_005923](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/2a449871-57b7-4f68-a32b-43f33af7b48a)

**Comment by CHNZYX** [comment]
重新校准试试？

**Comment by 246182606** [comment]
> 重新校准试试？

仍复现
![2023-06-21_013339](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/f51570d2-2ce0-4938-b960-8e9ecfcc1ec9)
![2023-06-21_013153](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/59857158/d7c32682-e27d-4fb0-92aa-97557cdce43c)

**Comment by 246182606** [comment]
大佬还没睡啊

**Comment by CHNZYX** [comment]
修了（大概），会在下个版本更新
