### ISSUE TITLE
新版本设定了自动使用沉浸器吗？

### ISSUE THREAD

**Issue by Achergo** [CHNZYX/Auto_Simulated_Universe#87]
我存的8个沉浸器全给用掉了，没看到文档相关说明，是哪里出了问题呀

**Comment by htshts1115** [comment]
+1难受，全给用掉了，也没看到注释。我把代码里沉浸奖励相关的都删了也没用

**Comment by CHNZYX** [comment]
确实有一段时间会无脑领沉浸奖励，今天中午的时候修复了。造成损失的话很抱歉
