### ISSUE TITLE
模擬宇宙六，這裡會卡住

### ISSUE THREAD

**Issue by seriaati** [CHNZYX/Auto_Simulated_Universe#88]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/61446626/c6788ad1-887b-456a-927d-fde8bb80b2a9)
腳本會一直按 W 往前走

**Comment by CHNZYX** [comment]
不清楚，暂离之后也这样吗

**Comment by seriaati** [comment]
不知道，還沒試過。
不確定我校準的方式是不是正確的：我傳送到黑塔辦公室後，鍵盤滑鼠都不動，直接按校正。傳送過去的時候視角是有稍微偏移的，並不是正面對著模擬宇宙入口。

**Comment by seriaati** [comment]
怎麼關了🤔
這個 issue 還沒確定解決吧

**Comment by CHNZYX** [comment]
没有后续反馈，没有人提出类似问题，所以关了。如果你还有问题，可以尝试更新版本，如果还是遇到可以附上日志文件。只有一张屏幕截图我很难去修复。
