### ISSUE TITLE
偶尔会出现走错路卡墙角然后循环

### ISSUE THREAD

**Issue by f59375543** [CHNZYX/Auto_Simulated_Universe#89]
复杂地形（比如说门口）走到那卡住，然后就会不停打开地图，关闭地图调整方向，然后打开地图，关闭地图调整方向，在此循环

能否假如循环多次后往后退几步，或者干脆直接结算关卡退出重新再打？

附上日志

[log.txt](https://github.com/CHNZYX/Auto_Simulated_Universe/files/11829455/log.txt)

**Comment by CHNZYX** [comment]
多次暂离无效后确实会结算的
