### ISSUE TITLE
Can you add english text along the original chinese text in the buttons of the GUI or add images of the GUI to the README_ENG.md?

### ISSUE THREAD

**Issue by FaZe-Goku** [CHNZYX/Auto_Simulated_Universe#94]
Understanding the meaning of the GUI's buttons just by seeing them instead of remembering the buttons's meaning will be very helpful for english readers

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/77009602/df285a13-bfa1-4184-81be-2dee1d60ef88)

**Comment by CHNZYX** [comment]
We will consider adding English language support in subsequent versions

**Comment by jason21415** [comment]
1.Calibration position
2.run
3.record map
4.Show CMD window
5.stop
6.setting
7.description
