### ISSUE TITLE
使用GUI版本，游戏画面按要求设置了，但校准出现问题

### ISSUE THREAD

**Issue by ShiroMaple** [CHNZYX/Auto_Simulated_Universe#99]
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/66283991/bd3c59c6-9cf8-4dbe-80b0-e68e7855df84)
点击校准后，游戏画面镜头转了两下就报错了

INFO [2023-07-02 03:07:23,524] [align_angle.py:32] 开始校准
WARNING [2023-07-02 03:07:23,782] [utils.py:86] 等待游戏窗口
[0]
E: 运行函数时出现错误
Traceback (most recent call last):
  File "gui\choose.py", line 31, in run
  File "align_angle.py", line 44, in main
  File "utils\utils.py", line 967, in mouse_move
OverflowError: cannot convert float infinity to integer

**Comment by melonedo** [comment]
校准这步需要会按下w键改变角度，如果没有成功发送w键的指令的话会导致角度不变（偏差为0），校准失败。可能的原因是没有管理员权限。

**Comment by mintsflandre** [comment]
游戏开窗口化了吗

**Comment by shawersky319** [comment]
根据我少量的试错经验，校准的时候要把游戏放在主显示器
